CREATE TABLE "glider_models" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	"manufacturer" text NOT NULL,
	"model" text NOT NULL,
	"size" text NOT NULL,
	"en_rating" text NOT NULL,
	"discipline" text NOT NULL,
	"catalog_status" text NOT NULL,
	"source_url" text NOT NULL,
	"sort_order" integer NOT NULL CONSTRAINT "glider_models_sort_order_unique" UNIQUE,
	CONSTRAINT "glider_models_manufacturer_model_size_unique" UNIQUE("manufacturer","model","size")
);
--> statement-breakpoint
INSERT INTO "glider_models" ("manufacturer", "model", "size", "en_rating", "discipline", "catalog_status", "source_url", "sort_order") VALUES
  ('Ozone', 'Moxie', 'XXS', 'A', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/moxie', 1),
  ('Ozone', 'Moxie', 'XS', 'A', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/moxie', 2),
  ('Ozone', 'Moxie', 'S', 'A', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/moxie', 3),
  ('Ozone', 'Moxie', 'M', 'A', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/moxie', 4),
  ('Ozone', 'Moxie', 'L', 'A', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/moxie', 5),
  ('Ozone', 'Moxie', 'XL', 'A', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/moxie', 6),
  ('Ozone', 'Alta GT', 'XXS', 'A', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/alta-gt', 7),
  ('Ozone', 'Alta GT', 'XS', 'A', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/alta-gt', 8),
  ('Ozone', 'Alta GT', 'S', 'A', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/alta-gt', 9),
  ('Ozone', 'Alta GT', 'M', 'A', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/alta-gt', 10),
  ('Ozone', 'Alta GT', 'L', 'A', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/alta-gt', 11),
  ('Ozone', 'Alta GT', 'XL', 'A', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/alta-gt', 12),
  ('Ozone', 'Buzz Z7', 'XS', 'B', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/buzz-z7', 13),
  ('Ozone', 'Buzz Z7', 'S', 'B', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/buzz-z7', 14),
  ('Ozone', 'Buzz Z7', 'MS', 'B', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/buzz-z7', 15),
  ('Ozone', 'Buzz Z7', 'ML', 'B', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/buzz-z7', 16),
  ('Ozone', 'Buzz Z7', 'L', 'B', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/buzz-z7', 17),
  ('Ozone', 'Buzz Z7', 'XL', 'B', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/buzz-z7', 18),
  ('Ozone', 'Geo 7', 'XS', 'B', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/geo-7', 19),
  ('Ozone', 'Geo 7', 'S', 'B', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/geo-7', 20),
  ('Ozone', 'Geo 7', 'MS', 'B', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/geo-7', 21),
  ('Ozone', 'Geo 7', 'ML', 'B', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/geo-7', 22),
  ('Ozone', 'Geo 7', 'L', 'B', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/geo-7', 23),
  ('Ozone', 'Vibe GT', 'XXS', 'A', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/vibe-gt', 24),
  ('Ozone', 'Vibe GT', 'XS', 'B', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/vibe-gt', 25),
  ('Ozone', 'Vibe GT', 'S', 'B', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/vibe-gt', 26),
  ('Ozone', 'Vibe GT', 'MS', 'B', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/vibe-gt', 27),
  ('Ozone', 'Vibe GT', 'ML', 'B', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/vibe-gt', 28),
  ('Ozone', 'Vibe GT', 'L', 'B', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/vibe-gt', 29),
  ('Ozone', 'Vibe GT', 'XL', 'B', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/vibe-gt', 30),
  ('Ozone', 'Rush 6', 'XS', 'B', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/rush-6', 31),
  ('Ozone', 'Rush 6', 'S', 'B', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/rush-6', 32),
  ('Ozone', 'Rush 6', 'MS', 'B', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/rush-6', 33),
  ('Ozone', 'Rush 6', 'ML', 'B', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/rush-6', 34),
  ('Ozone', 'Rush 6', 'L', 'B', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/rush-6', 35),
  ('Ozone', 'Rush 6', 'XL', 'B', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/rush-6', 36),
  ('Ozone', 'Swift 6', 'XS', 'B', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/swift-6', 37),
  ('Ozone', 'Swift 6', 'S', 'B', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/swift-6', 38),
  ('Ozone', 'Swift 6', 'MS', 'B', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/swift-6', 39),
  ('Ozone', 'Swift 6', 'ML', 'B', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/swift-6', 40),
  ('Ozone', 'Swift 6', 'L', 'B', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/swift-6', 41),
  ('Ozone', 'Delta 5', 'XS', 'C', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/delta-5', 42),
  ('Ozone', 'Delta 5', 'S', 'C', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/delta-5', 43),
  ('Ozone', 'Delta 5', 'MS', 'C', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/delta-5', 44),
  ('Ozone', 'Delta 5', 'ML', 'C', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/delta-5', 45),
  ('Ozone', 'Delta 5', 'L', 'C', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/delta-5', 46),
  ('Ozone', 'Delta 5', 'XL', 'C', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/delta-5', 47),
  ('Ozone', 'Alpina 4', 'XS', 'C', 'Paraglider', 'Recent previous', 'https://flyozone.com/paragliders/products/gliders/alpina-4', 48),
  ('Ozone', 'Alpina 4', 'S', 'C', 'Paraglider', 'Recent previous', 'https://flyozone.com/paragliders/products/gliders/alpina-4', 49),
  ('Ozone', 'Alpina 4', 'MS', 'C', 'Paraglider', 'Recent previous', 'https://flyozone.com/paragliders/products/gliders/alpina-4', 50),
  ('Ozone', 'Alpina 4', 'ML', 'C', 'Paraglider', 'Recent previous', 'https://flyozone.com/paragliders/products/gliders/alpina-4', 51),
  ('Ozone', 'Alpina 4', 'L', 'C', 'Paraglider', 'Recent previous', 'https://flyozone.com/paragliders/products/gliders/alpina-4', 52),
  ('Ozone', 'Alpina 4 GT', 'XS', 'C', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/alpina-4-gt', 53),
  ('Ozone', 'Alpina 4 GT', 'S', 'C', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/alpina-4-gt', 54),
  ('Ozone', 'Alpina 4 GT', 'MS', 'C', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/alpina-4-gt', 55),
  ('Ozone', 'Alpina 4 GT', 'ML', 'C', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/alpina-4-gt', 56),
  ('Ozone', 'Alpina 4 GT', 'L', 'C', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/alpina-4-gt', 57),
  ('Ozone', 'Alpina 4 GT', 'XL', 'C', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/alpina-4-gt', 58),
  ('Ozone', 'Alpina 5', 'XS', 'C', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/alpina-5', 59),
  ('Ozone', 'Alpina 5', 'S', 'C', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/alpina-5', 60),
  ('Ozone', 'Alpina 5', 'MS', 'C', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/alpina-5', 61),
  ('Ozone', 'Alpina 5', 'ML', 'C', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/alpina-5', 62),
  ('Ozone', 'Alpina 5', 'L', 'C', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/alpina-5', 63),
  ('Ozone', 'Alpina 5', 'XL', 'C', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/alpina-5', 64),
  ('Ozone', 'Photon', 'XS', 'C', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/photon', 65),
  ('Ozone', 'Photon', 'S', 'C', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/photon', 66),
  ('Ozone', 'Photon', 'MS', 'C', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/photon', 67),
  ('Ozone', 'Photon', 'ML', 'C', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/photon', 68),
  ('Ozone', 'Photon', 'L', 'C', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/photon', 69),
  ('Ozone', 'Photon', 'XL', 'C', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/photon', 70),
  ('Ozone', 'Lyght', 'XS', 'C', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/lyght', 71),
  ('Ozone', 'Lyght', 'S', 'C', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/lyght', 72),
  ('Ozone', 'Lyght', 'MS', 'C', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/lyght', 73),
  ('Ozone', 'Lyght', 'ML', 'C', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/lyght', 74),
  ('Ozone', 'Lyght', 'L', 'C', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/lyght', 75),
  ('Ozone', 'Zeolite 2 GT', 'XS', 'D', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/zeolite-2-gt', 76),
  ('Ozone', 'Zeolite 2 GT', 'S', 'D', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/zeolite-2-gt', 77),
  ('Ozone', 'Zeolite 2 GT', 'MS', 'D', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/zeolite-2-gt', 78),
  ('Ozone', 'Zeolite 2 GT', 'ML', 'D', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/zeolite-2-gt', 79),
  ('Ozone', 'Zeolite 2 GT', 'L', 'D', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/zeolite-2-gt', 80),
  ('Ozone', 'Zeolite 2', 'XS', 'D', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/zeolite-2', 81),
  ('Ozone', 'Zeolite 2', 'S', 'D', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/zeolite-2', 82),
  ('Ozone', 'Zeolite 2', 'MS', 'D', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/zeolite-2', 83),
  ('Ozone', 'Zeolite 2', 'ML', 'D', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/zeolite-2', 84),
  ('Ozone', 'Zeno 2', 'XS', 'D', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/zeno-2', 85),
  ('Ozone', 'Zeno 2', 'S', 'D', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/zeno-2', 86),
  ('Ozone', 'Zeno 2', 'MS', 'D', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/zeno-2', 87),
  ('Ozone', 'Zeno 2', 'ML', 'D', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/zeno-2', 88),
  ('Ozone', 'Zeno 2', 'L', 'D', 'Paraglider', 'Current', 'https://flyozone.com/paragliders/products/gliders/zeno-2', 89),
  ('Ozone', 'Enzo 3', 'XXS', 'CCC', 'Competition', 'Current', 'https://flyozone.com/paragliders/products/gliders/enzo-3', 90),
  ('Ozone', 'Enzo 3', 'XS', 'CCC', 'Competition', 'Current', 'https://flyozone.com/paragliders/products/gliders/enzo-3', 91),
  ('Ozone', 'Enzo 3', 'S', 'CCC', 'Competition', 'Current', 'https://flyozone.com/paragliders/products/gliders/enzo-3', 92),
  ('Ozone', 'Enzo 3', 'M', 'CCC', 'Competition', 'Current', 'https://flyozone.com/paragliders/products/gliders/enzo-3', 93),
  ('Ozone', 'Enzo 3', 'L', 'CCC', 'Competition', 'Current', 'https://flyozone.com/paragliders/products/gliders/enzo-3', 94),
  ('Ozone', 'Enzo 3', 'XL', 'CCC', 'Competition', 'Current', 'https://flyozone.com/paragliders/products/gliders/enzo-3', 95),
  ('Ozone', 'Ultralite 5', '13', 'Uncertified', 'Hike and fly', 'Current', 'https://flyozone.com/paragliders/products/gliders/ultralite-5', 96),
  ('Ozone', 'Ultralite 5', '15', 'Uncertified', 'Hike and fly', 'Current', 'https://flyozone.com/paragliders/products/gliders/ultralite-5', 97),
  ('Ozone', 'Ultralite 5', '17', 'C', 'Hike and fly', 'Current', 'https://flyozone.com/paragliders/products/gliders/ultralite-5', 98),
  ('Ozone', 'Ultralite 5', '19', 'B', 'Hike and fly', 'Current', 'https://flyozone.com/paragliders/products/gliders/ultralite-5', 99),
  ('Ozone', 'Ultralite 5', '21', 'A', 'Hike and fly', 'Current', 'https://flyozone.com/paragliders/products/gliders/ultralite-5', 100),
  ('Ozone', 'Ultralite 5', '23', 'A', 'Hike and fly', 'Current', 'https://flyozone.com/paragliders/products/gliders/ultralite-5', 101),
  ('Ozone', 'Ultralite 5', '25', 'A', 'Hike and fly', 'Current', 'https://flyozone.com/paragliders/products/gliders/ultralite-5', 102),
  ('Ozone', 'Session', '15', 'Load test', 'Acro', 'Current', 'https://flyozone.com/paragliders/products/gliders/session', 103),
  ('Ozone', 'Session', '16', 'Load test', 'Acro', 'Current', 'https://flyozone.com/paragliders/products/gliders/session', 104),
  ('Ozone', 'Session', '17', 'Load test', 'Acro', 'Current', 'https://flyozone.com/paragliders/products/gliders/session', 105),
  ('Ozone', 'Magnum 4', '38', 'B', 'Tandem', 'Current', 'https://flyozone.com/paragliders/products/gliders/magnum-4', 106),
  ('Ozone', 'Magnum 4', '41', 'B', 'Tandem', 'Current', 'https://flyozone.com/paragliders/products/gliders/magnum-4', 107),
  ('Ozone', 'Magnum 4', '44', 'B', 'Tandem', 'Current', 'https://flyozone.com/paragliders/products/gliders/magnum-4', 108),
  ('Ozone', 'Swiftmax 2', '41', 'B', 'Tandem', 'Current', 'https://flyozone.com/paragliders/products/gliders/swiftmax-2', 109),
  ('Ozone', 'Wisp 2', '37', 'B', 'Tandem', 'Current', 'https://flyozone.com/paragliders/products/gliders/wisp-2', 110),
  ('Gradient', 'GO', '24', 'A', 'Paraglider', 'Legacy reference', 'https://service.dhv.de/db3/muster/liste?fhersteller=Gradient&fmuster=&lang=en&s=1', 111),
  ('Gradient', 'GO', '26', 'A', 'Paraglider', 'Legacy reference', 'https://service.dhv.de/db3/muster/liste?fhersteller=Gradient&fmuster=&lang=en&s=1', 112),
  ('Gradient', 'GO', '28', 'A', 'Paraglider', 'Legacy reference', 'https://service.dhv.de/db3/muster/liste?fhersteller=Gradient&fmuster=&lang=en&s=1', 113),
  ('Gradient', 'GO', '30', 'A', 'Paraglider', 'Legacy reference', 'https://service.dhv.de/db3/muster/liste?fhersteller=Gradient&fmuster=&lang=en&s=1', 114),
  ('UP', 'RIMO 2', 'XS', 'A', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/rimo-2', 115),
  ('UP', 'RIMO 2', 'S', 'A', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/rimo-2', 116),
  ('UP', 'RIMO 2', 'SM', 'A', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/rimo-2', 117),
  ('UP', 'RIMO 2', 'M', 'A', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/rimo-2', 118),
  ('UP', 'RIMO 2', 'L', 'A', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/rimo-2', 119),
  ('UP', 'MANA 2', '21', 'A/B', 'Hike and fly', 'Current', 'https://www.up-paragliders.com/paragliders/mana-2', 120),
  ('UP', 'MANA 2', '23', 'A', 'Hike and fly', 'Current', 'https://www.up-paragliders.com/paragliders/mana-2', 121),
  ('UP', 'MANA 2', '25', 'A', 'Hike and fly', 'Current', 'https://www.up-paragliders.com/paragliders/mana-2', 122),
  ('UP', 'MANA 2', '27', 'A', 'Hike and fly', 'Current', 'https://www.up-paragliders.com/paragliders/mana-2', 123),
  ('UP', 'DENA', 'XS', 'A', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/dena', 124),
  ('UP', 'DENA', 'S', 'A', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/dena', 125),
  ('UP', 'DENA', 'S/M', 'A', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/dena', 126),
  ('UP', 'DENA', 'M', 'A', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/dena', 127),
  ('UP', 'DENA', 'L', 'A', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/dena', 128),
  ('UP', 'MAKALU 5', 'S', 'B', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/makalu-5', 129),
  ('UP', 'MAKALU 5', 'SM', 'B', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/makalu-5', 130),
  ('UP', 'MAKALU 5', 'M', 'B', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/makalu-5', 131),
  ('UP', 'MAKALU 5', 'L', 'B', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/makalu-5', 132),
  ('UP', 'KIBO X', 'XS', 'B', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/kibo-x', 133),
  ('UP', 'KIBO X', 'S', 'B', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/kibo-x', 134),
  ('UP', 'KIBO X', 'S/M', 'B', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/kibo-x', 135),
  ('UP', 'KIBO X', 'M', 'B', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/kibo-x', 136),
  ('UP', 'KIBO X', 'L', 'B', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/kibo-x', 137),
  ('UP', 'LHOTSE X', 'XS', 'B', 'Hike and fly', 'Current', 'https://www.up-paragliders.com/paragliders/lhotse-x', 138),
  ('UP', 'LHOTSE X', 'S', 'B', 'Hike and fly', 'Current', 'https://www.up-paragliders.com/paragliders/lhotse-x', 139),
  ('UP', 'LHOTSE X', 'SM', 'B', 'Hike and fly', 'Current', 'https://www.up-paragliders.com/paragliders/lhotse-x', 140),
  ('UP', 'LHOTSE X', 'M', 'B', 'Hike and fly', 'Current', 'https://www.up-paragliders.com/paragliders/lhotse-x', 141),
  ('UP', 'SUMMIT X', 'S', 'B', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/summit-x', 142),
  ('UP', 'SUMMIT X', 'SM', 'B', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/summit-x', 143),
  ('UP', 'SUMMIT X', 'M', 'B', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/summit-x', 144),
  ('UP', 'SUMMIT X', 'L', 'B', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/summit-x', 145),
  ('UP', 'KANGRI X', '21', 'B', 'Hike and fly', 'Current', 'https://www.up-paragliders.com/paragliders/kangri-x', 146),
  ('UP', 'KANGRI X', '23', 'B', 'Hike and fly', 'Current', 'https://www.up-paragliders.com/paragliders/kangri-x', 147),
  ('UP', 'KANGRI X', '25', 'B', 'Hike and fly', 'Current', 'https://www.up-paragliders.com/paragliders/kangri-x', 148),
  ('UP', 'KAILASH', '16', 'C', 'Miniwing', 'Current', 'https://www.up-paragliders.com/paragliders/kailash', 149),
  ('UP', 'KAILASH', '19', 'C', 'Miniwing', 'Current', 'https://www.up-paragliders.com/paragliders/kailash', 150),
  ('UP', 'TRANGO X', 'S', 'C', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/trango-x', 151),
  ('UP', 'TRANGO X', 'SM', 'C', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/trango-x', 152),
  ('UP', 'TRANGO X', 'M', 'C', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/trango-x', 153),
  ('UP', 'TRANGO X', 'L', 'C', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/trango-x', 154),
  ('UP', 'TORRE', 'S', 'C', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/torre', 155),
  ('UP', 'TORRE', 'SM', 'C', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/torre', 156),
  ('UP', 'TORRE', 'M', 'C', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/torre', 157),
  ('UP', 'TORRE', 'L', 'C', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/torre', 158),
  ('UP', 'TORRE', 'XL', 'C', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/torre', 159),
  ('UP', 'MERU 2', 'S', 'D', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/meru-2', 160),
  ('UP', 'MERU 2', 'S/M', 'D', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/meru-2', 161),
  ('UP', 'MERU 2', 'M', 'D', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/meru-2', 162),
  ('UP', 'MERU 2', 'L', 'D', 'Paraglider', 'Current', 'https://www.up-paragliders.com/paragliders/meru-2', 163),
  ('UP', 'MISTI', '14', 'Load test', 'Acro and freestyle', 'Current', 'https://www.up-paragliders.com/paragliders/misti', 164),
  ('UP', 'MISTI', '16', 'Load test', 'Acro and freestyle', 'Current', 'https://www.up-paragliders.com/paragliders/misti', 165),
  ('UP', 'MISTI', '18', 'Load test', 'Acro and freestyle', 'Current', 'https://www.up-paragliders.com/paragliders/misti', 166),
  ('UP', 'MISTI', '20', 'Load test', 'Acro and freestyle', 'Current', 'https://www.up-paragliders.com/paragliders/misti', 167),
  ('UP', 'MISTI', '22', 'Load test', 'Acro and freestyle', 'Current', 'https://www.up-paragliders.com/paragliders/misti', 168),
  ('UP', 'MISTI', '24', 'Load test', 'Acro and freestyle', 'Current', 'https://www.up-paragliders.com/paragliders/misti', 169),
  ('UP', 'MISTI', '33 Bi', 'Load test', 'Acro and freestyle', 'Current', 'https://www.up-paragliders.com/paragliders/misti', 170),
  ('UP', 'K2 5', '38', 'B', 'Tandem', 'Current', 'https://www.up-paragliders.com/paragliders/k2-5', 171),
  ('UP', 'K2 5', '41', 'B', 'Tandem', 'Current', 'https://www.up-paragliders.com/paragliders/k2-5', 172),
  ('UP', 'K2 5', '44', 'B', 'Tandem', 'Current', 'https://www.up-paragliders.com/paragliders/k2-5', 173),
  ('Niviuk', 'Koyot 6', '20', 'A', 'Paraglider', 'Current', 'https://niviuk.com/en/koyot-6', 174),
  ('Niviuk', 'Koyot 6', '22', 'A', 'Paraglider', 'Current', 'https://niviuk.com/en/koyot-6', 175),
  ('Niviuk', 'Koyot 6', '24', 'A', 'Paraglider', 'Current', 'https://niviuk.com/en/koyot-6', 176),
  ('Niviuk', 'Koyot 6', '26', 'A', 'Paraglider', 'Current', 'https://niviuk.com/en/koyot-6', 177),
  ('Niviuk', 'Koyot 6', '28', 'A', 'Paraglider', 'Current', 'https://niviuk.com/en/koyot-6', 178),
  ('Niviuk', 'Koyot 6', '30', 'A', 'Paraglider', 'Current', 'https://niviuk.com/en/koyot-6', 179),
  ('Niviuk', 'Hook 6', '20', 'B', 'Paraglider', 'Current', 'https://niviuk.com/en/hook-6', 180),
  ('Niviuk', 'Hook 6', '22', 'B', 'Paraglider', 'Current', 'https://niviuk.com/en/hook-6', 181),
  ('Niviuk', 'Hook 6', '24', 'B', 'Paraglider', 'Current', 'https://niviuk.com/en/hook-6', 182),
  ('Niviuk', 'Hook 6', '26', 'B', 'Paraglider', 'Current', 'https://niviuk.com/en/hook-6', 183),
  ('Niviuk', 'Hook 6', '28', 'B', 'Paraglider', 'Current', 'https://niviuk.com/en/hook-6', 184),
  ('Niviuk', 'Hook 6', '31', 'B', 'Paraglider', 'Current', 'https://niviuk.com/en/hook-6', 185),
  ('Niviuk', 'Hiko', '20', 'B', 'Paraglider', 'Current', 'https://niviuk.com/en/hiko', 186),
  ('Niviuk', 'Hiko', '22', 'B', 'Paraglider', 'Current', 'https://niviuk.com/en/hiko', 187),
  ('Niviuk', 'Hiko', '24', 'B', 'Paraglider', 'Current', 'https://niviuk.com/en/hiko', 188),
  ('Niviuk', 'Hiko', '26', 'B', 'Paraglider', 'Current', 'https://niviuk.com/en/hiko', 189),
  ('Niviuk', 'Hiko', '28', 'B', 'Paraglider', 'Current', 'https://niviuk.com/en/hiko', 190),
  ('Niviuk', 'Hiko', '30', 'B', 'Paraglider', 'Current', 'https://niviuk.com/en/hiko', 191),
  ('Niviuk', 'Ikuma 3', '20', 'B+', 'Paraglider', 'Current', 'https://niviuk.com/en/ikuma-3', 192),
  ('Niviuk', 'Ikuma 3', '22', 'B+', 'Paraglider', 'Current', 'https://niviuk.com/en/ikuma-3', 193),
  ('Niviuk', 'Ikuma 3', '24', 'B+', 'Paraglider', 'Current', 'https://niviuk.com/en/ikuma-3', 194),
  ('Niviuk', 'Ikuma 3', '26', 'B+', 'Paraglider', 'Current', 'https://niviuk.com/en/ikuma-3', 195),
  ('Niviuk', 'Ikuma 3', '28', 'B+', 'Paraglider', 'Current', 'https://niviuk.com/en/ikuma-3', 196),
  ('Niviuk', 'Ikuma 3', '30', 'B+', 'Paraglider', 'Current', 'https://niviuk.com/en/ikuma-3', 197),
  ('Niviuk', 'Artik R 2', '20', 'C', 'Paraglider', 'Current', 'https://niviuk.com/en/artik-r-2', 198),
  ('Niviuk', 'Artik R 2', '21', 'C', 'Paraglider', 'Current', 'https://niviuk.com/en/artik-r-2', 199),
  ('Niviuk', 'Artik R 2', '23', 'C', 'Paraglider', 'Current', 'https://niviuk.com/en/artik-r-2', 200),
  ('Niviuk', 'Artik R 2', '24', 'C', 'Paraglider', 'Current', 'https://niviuk.com/en/artik-r-2', 201),
  ('Niviuk', 'Artik R 2', '25', 'C', 'Paraglider', 'Current', 'https://niviuk.com/en/artik-r-2', 202),
  ('Niviuk', 'Artik R 2', '27', 'C', 'Paraglider', 'Current', 'https://niviuk.com/en/artik-r-2', 203),
  ('Niviuk', 'Peak 6', '21', 'D', 'Paraglider', 'Current', 'https://niviuk.com/en/peak-6', 204),
  ('Niviuk', 'Peak 6', '22', 'D', 'Paraglider', 'Current', 'https://niviuk.com/en/peak-6', 205),
  ('Niviuk', 'Peak 6', '24', 'D', 'Paraglider', 'Current', 'https://niviuk.com/en/peak-6', 206),
  ('Niviuk', 'Peak 6', '26', 'D', 'Paraglider', 'Current', 'https://niviuk.com/en/peak-6', 207),
  ('Niviuk', 'Icepeak X-One', '20', 'CCC', 'Competition', 'Current', 'https://niviuk.com/en/icepeak-x-one', 208),
  ('Niviuk', 'Icepeak X-One', '22', 'CCC', 'Competition', 'Current', 'https://niviuk.com/en/icepeak-x-one', 209),
  ('Niviuk', 'Icepeak X-One', '24', 'CCC', 'Competition', 'Current', 'https://niviuk.com/en/icepeak-x-one', 210),
  ('Niviuk', 'Icepeak X-One', '25', 'CCC', 'Competition', 'Current', 'https://niviuk.com/en/icepeak-x-one', 211),
  ('Niviuk', 'Icepeak X-One', '26', 'CCC', 'Competition', 'Current', 'https://niviuk.com/en/icepeak-x-one', 212),
  ('Niviuk', 'Bi Roller 2', '30', 'B', 'Tandem and acro', 'Current', 'https://niviuk.com/en/bi-roller-2', 213),
  ('Niviuk', 'Bi Roller 2', '34', 'B', 'Tandem and acro', 'Current', 'https://niviuk.com/en/bi-roller-2', 214),
  ('Niviuk', 'Jester', '14', 'EN 926-1', 'Acro', 'Current', 'https://niviuk.com/en/jester', 215),
  ('Niviuk', 'Jester', '16', 'EN 926-1', 'Acro', 'Current', 'https://niviuk.com/en/jester', 216),
  ('Niviuk', 'Jester', '18', 'EN 926-1', 'Acro', 'Current', 'https://niviuk.com/en/jester', 217),
  ('Niviuk', 'Jester', '21', 'EN 926-1', 'Acro', 'Current', 'https://niviuk.com/en/jester', 218),
  ('Niviuk', 'Jester', '24', 'EN 926-1', 'Acro', 'Current', 'https://niviuk.com/en/jester', 219),
  ('Niviuk', 'Target', '20', 'A', 'Accuracy', 'Current', 'https://niviuk.com/en/target', 220),
  ('Niviuk', 'Target', '22', 'A', 'Accuracy', 'Current', 'https://niviuk.com/en/target', 221),
  ('Niviuk', 'Target', '24', 'A', 'Accuracy', 'Current', 'https://niviuk.com/en/target', 222),
  ('Niviuk', 'Target', '26', 'A', 'Accuracy', 'Current', 'https://niviuk.com/en/target', 223),
  ('Niviuk', 'Target', '28', 'A', 'Accuracy', 'Current', 'https://niviuk.com/en/target', 224),
  ('Niviuk', 'Target', '30', 'A', 'Accuracy', 'Current', 'https://niviuk.com/en/target', 225),
  ('Niviuk', 'Takoo 6', '38', 'B', 'Tandem', 'Current', 'https://niviuk.com/en/takoo-6', 226),
  ('Niviuk', 'Takoo 6', '41', 'B', 'Tandem', 'Current', 'https://niviuk.com/en/takoo-6', 227),
  ('Niviuk', 'Takoo 6', '44', 'B', 'Tandem', 'Current', 'https://niviuk.com/en/takoo-6', 228),
  ('Niviuk', 'Koyot 6 P', '20', 'A', 'Hike and fly', 'Current', 'https://niviuk.com/en/koyot-6-p', 229),
  ('Niviuk', 'Koyot 6 P', '22', 'A', 'Hike and fly', 'Current', 'https://niviuk.com/en/koyot-6-p', 230),
  ('Niviuk', 'Koyot 6 P', '24', 'A', 'Hike and fly', 'Current', 'https://niviuk.com/en/koyot-6-p', 231),
  ('Niviuk', 'Koyot 6 P', '26', 'A', 'Hike and fly', 'Current', 'https://niviuk.com/en/koyot-6-p', 232),
  ('Niviuk', 'Koyot 6 P', '28', 'A', 'Hike and fly', 'Current', 'https://niviuk.com/en/koyot-6-p', 233),
  ('Niviuk', 'Hook 6 P', '20', 'B', 'Hike and fly', 'Current', 'https://niviuk.com/en/hook-6-p', 234),
  ('Niviuk', 'Hook 6 P', '22', 'A+', 'Hike and fly', 'Current', 'https://niviuk.com/en/hook-6-p', 235),
  ('Niviuk', 'Hook 6 P', '24', 'A+', 'Hike and fly', 'Current', 'https://niviuk.com/en/hook-6-p', 236),
  ('Niviuk', 'Hook 6 P', '26', 'A+', 'Hike and fly', 'Current', 'https://niviuk.com/en/hook-6-p', 237),
  ('Niviuk', 'Hook 6 P', '28', 'A+', 'Hike and fly', 'Current', 'https://niviuk.com/en/hook-6-p', 238),
  ('Niviuk', 'Kode 2 P', '12', 'Uncertified', 'Hike and fly and miniwing', 'Current', 'https://niviuk.com/en/kode-2-p', 239),
  ('Niviuk', 'Kode 2 P', '14', 'D', 'Hike and fly and miniwing', 'Current', 'https://niviuk.com/en/kode-2-p', 240),
  ('Niviuk', 'Kode 2 P', '16', 'C', 'Hike and fly and miniwing', 'Current', 'https://niviuk.com/en/kode-2-p', 241),
  ('Niviuk', 'Kode 2 P', '18', 'A/C', 'Hike and fly and miniwing', 'Current', 'https://niviuk.com/en/kode-2-p', 242),
  ('Niviuk', 'Kode 2 P', '20', 'A/B', 'Hike and fly and miniwing', 'Current', 'https://niviuk.com/en/kode-2-p', 243),
  ('Niviuk', 'Kode 2 P', '22', 'A', 'Hike and fly and miniwing', 'Current', 'https://niviuk.com/en/kode-2-p', 244),
  ('Niviuk', 'Kode 2 P', '24', 'A', 'Hike and fly and miniwing', 'Current', 'https://niviuk.com/en/kode-2-p', 245),
  ('Niviuk', 'Kode 2 P', '26', 'A', 'Hike and fly and miniwing', 'Current', 'https://niviuk.com/en/kode-2-p', 246),
  ('Niviuk', 'Hiko P', '20', 'B', 'Hike and fly', 'Current', 'https://niviuk.com/en/hiko-p', 247),
  ('Niviuk', 'Hiko P', '22', 'B', 'Hike and fly', 'Current', 'https://niviuk.com/en/hiko-p', 248),
  ('Niviuk', 'Hiko P', '24', 'B', 'Hike and fly', 'Current', 'https://niviuk.com/en/hiko-p', 249),
  ('Niviuk', 'Hiko P', '26', 'B', 'Hike and fly', 'Current', 'https://niviuk.com/en/hiko-p', 250),
  ('Niviuk', 'Hiko P', '28', 'B', 'Hike and fly', 'Current', 'https://niviuk.com/en/hiko-p', 251),
  ('Niviuk', 'Ikuma 3 P', '20', 'B+', 'Hike and fly', 'Current', 'https://niviuk.com/en/ikuma-3-p', 252),
  ('Niviuk', 'Ikuma 3 P', '22', 'B+', 'Hike and fly', 'Current', 'https://niviuk.com/en/ikuma-3-p', 253),
  ('Niviuk', 'Ikuma 3 P', '24', 'B+', 'Hike and fly', 'Current', 'https://niviuk.com/en/ikuma-3-p', 254),
  ('Niviuk', 'Ikuma 3 P', '26', 'B+', 'Hike and fly', 'Current', 'https://niviuk.com/en/ikuma-3-p', 255),
  ('Niviuk', 'Ikuma 3 P', '28', 'B+', 'Hike and fly', 'Current', 'https://niviuk.com/en/ikuma-3-p', 256),
  ('Niviuk', 'Artik 7 P', '20', 'C', 'Hike and fly', 'Current', 'https://niviuk.com/en/artik-7-p', 257),
  ('Niviuk', 'Artik 7 P', '22', 'C', 'Hike and fly', 'Current', 'https://niviuk.com/en/artik-7-p', 258),
  ('Niviuk', 'Artik 7 P', '23', 'C', 'Hike and fly', 'Current', 'https://niviuk.com/en/artik-7-p', 259),
  ('Niviuk', 'Artik 7 P', '24', 'C', 'Hike and fly', 'Current', 'https://niviuk.com/en/artik-7-p', 260),
  ('Niviuk', 'Artik 7 P', '26', 'C', 'Hike and fly', 'Current', 'https://niviuk.com/en/artik-7-p', 261),
  ('Niviuk', 'Artik 7 P', '28', 'C', 'Hike and fly', 'Current', 'https://niviuk.com/en/artik-7-p', 262),
  ('Niviuk', 'Klimber 3 P', '20', 'D', 'Hike and fly', 'Current', 'https://niviuk.com/en/klimber-3-p', 263),
  ('Niviuk', 'Klimber 3 P', '22', 'D', 'Hike and fly', 'Current', 'https://niviuk.com/en/klimber-3-p', 264),
  ('Niviuk', 'Klimber 3 P', '24', 'D', 'Hike and fly', 'Current', 'https://niviuk.com/en/klimber-3-p', 265),
  ('Niviuk', 'Klimber 3 P', '26', 'D', 'Hike and fly', 'Current', 'https://niviuk.com/en/klimber-3-p', 266),
  ('Niviuk', 'Skin 4 P', '14', 'C', 'Single surface', 'Current', 'https://niviuk.com/en/skin-4-p', 267),
  ('Niviuk', 'Skin 4 P', '16', 'B', 'Single surface', 'Current', 'https://niviuk.com/en/skin-4-p', 268),
  ('Niviuk', 'Skin 4 P', '18', 'B', 'Single surface', 'Current', 'https://niviuk.com/en/skin-4-p', 269),
  ('Niviuk', 'Skin 4 P', '20', 'B', 'Single surface', 'Current', 'https://niviuk.com/en/skin-4-p', 270),
  ('Niviuk', 'Bi Skin 2 P', '31', 'B', 'Single surface tandem', 'Current', 'https://niviuk.com/en/bi-skin-2-p', 271),
  ('Gin', 'Yeti 6', '21', 'A', 'Hike and fly', 'Current', 'https://www.gingliders.com/en/paragliders/beginner-and-intermediate/yeti-6/', 272),
  ('Gin', 'Yeti 6', '23', 'A', 'Hike and fly', 'Current', 'https://www.gingliders.com/en/paragliders/beginner-and-intermediate/yeti-6/', 273),
  ('Gin', 'Yeti 6', '25', 'A', 'Hike and fly', 'Current', 'https://www.gingliders.com/en/paragliders/beginner-and-intermediate/yeti-6/', 274),
  ('Gin', 'Yeti 6', '27', 'A', 'Hike and fly', 'Current', 'https://www.gingliders.com/en/paragliders/beginner-and-intermediate/yeti-6/', 275),
  ('Gin', 'Bolero 8', 'XXS', 'A', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/beginner-and-intermediate/bolero-8/', 276),
  ('Gin', 'Bolero 8', 'XS', 'A', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/beginner-and-intermediate/bolero-8/', 277),
  ('Gin', 'Bolero 8', 'S', 'A', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/beginner-and-intermediate/bolero-8/', 278),
  ('Gin', 'Bolero 8', 'M', 'A', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/beginner-and-intermediate/bolero-8/', 279),
  ('Gin', 'Bolero 8', 'L', 'A', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/beginner-and-intermediate/bolero-8/', 280),
  ('Gin', 'Elise', 'XXS', 'A', 'Light paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/beginner-and-intermediate/elise/', 281),
  ('Gin', 'Elise', 'XS', 'A', 'Light paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/beginner-and-intermediate/elise/', 282),
  ('Gin', 'Elise', 'S', 'A', 'Light paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/beginner-and-intermediate/elise/', 283),
  ('Gin', 'Elise', 'M', 'A', 'Light paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/beginner-and-intermediate/elise/', 284),
  ('Gin', 'Elise', 'L', 'A', 'Light paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/beginner-and-intermediate/elise/', 285),
  ('Gin', 'Calypso 2', 'XXS', 'B', 'Light paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/beginner-and-intermediate/calypso-2/', 286),
  ('Gin', 'Calypso 2', 'XS', 'B', 'Light paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/beginner-and-intermediate/calypso-2/', 287),
  ('Gin', 'Calypso 2', 'S', 'B', 'Light paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/beginner-and-intermediate/calypso-2/', 288),
  ('Gin', 'Calypso 2', 'M', 'B', 'Light paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/beginner-and-intermediate/calypso-2/', 289),
  ('Gin', 'Calypso 2', 'L', 'B', 'Light paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/beginner-and-intermediate/calypso-2/', 290),
  ('Gin', 'Evora', 'XXS', 'B', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/beginner-and-intermediate/evora/', 291),
  ('Gin', 'Evora', 'XS', 'B', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/beginner-and-intermediate/evora/', 292),
  ('Gin', 'Evora', 'S', 'B', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/beginner-and-intermediate/evora/', 293),
  ('Gin', 'Evora', 'M', 'B', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/beginner-and-intermediate/evora/', 294),
  ('Gin', 'Evora', 'L', 'B', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/beginner-and-intermediate/evora/', 295),
  ('Gin', 'Evora', 'XL', 'B', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/beginner-and-intermediate/evora/', 296),
  ('Gin', 'Bandit 2', 'XXS', 'B', 'Light paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/beginner-and-intermediate/bandit-2/', 297),
  ('Gin', 'Bandit 2', 'XS', 'B', 'Light paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/beginner-and-intermediate/bandit-2/', 298),
  ('Gin', 'Bandit 2', 'S', 'B', 'Light paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/beginner-and-intermediate/bandit-2/', 299),
  ('Gin', 'Bandit 2', 'M', 'B', 'Light paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/beginner-and-intermediate/bandit-2/', 300),
  ('Gin', 'Bandit 2', 'L', 'B', 'Light paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/beginner-and-intermediate/bandit-2/', 301),
  ('Gin', 'Avid', 'XXS', 'B', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/sport/avid/', 302),
  ('Gin', 'Avid', 'XS', 'B', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/sport/avid/', 303),
  ('Gin', 'Avid', 'S', 'B', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/sport/avid/', 304),
  ('Gin', 'Avid', 'M', 'B', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/sport/avid/', 305),
  ('Gin', 'Avid', 'L', 'B', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/sport/avid/', 306),
  ('Gin', 'Explorer 2', 'XXS', 'B', 'Light paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/sport/explorer-2/', 307),
  ('Gin', 'Explorer 2', 'XS', 'B', 'Light paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/sport/explorer-2/', 308),
  ('Gin', 'Explorer 2', 'S', 'B', 'Light paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/sport/explorer-2/', 309),
  ('Gin', 'Explorer 2', 'M', 'B', 'Light paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/sport/explorer-2/', 310),
  ('Gin', 'Explorer 2', 'L', 'B', 'Light paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/sport/explorer-2/', 311),
  ('Gin', 'Bonanza 3', 'XXS', 'C', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/sport/bonanza-3/', 312),
  ('Gin', 'Bonanza 3', 'XS', 'C', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/sport/bonanza-3/', 313),
  ('Gin', 'Bonanza 3', 'S', 'C', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/sport/bonanza-3/', 314),
  ('Gin', 'Bonanza 3', 'M', 'C', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/sport/bonanza-3/', 315),
  ('Gin', 'Bonanza 3', 'L', 'C', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/sport/bonanza-3/', 316),
  ('Gin', 'Camino 2', 'XXS', 'C', 'Light paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/sport/camino-2/', 317),
  ('Gin', 'Camino 2', 'XS', 'C', 'Light paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/sport/camino-2/', 318),
  ('Gin', 'Camino 2', 'S', 'C', 'Light paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/sport/camino-2/', 319),
  ('Gin', 'Camino 2', 'M', 'C', 'Light paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/sport/camino-2/', 320),
  ('Gin', 'Camino 2', 'L', 'C', 'Light paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/sport/camino-2/', 321),
  ('Gin', 'GTO 3', 'XXS', 'C', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/sport/gto-3/', 322),
  ('Gin', 'GTO 3', 'XS', 'C', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/sport/gto-3/', 323),
  ('Gin', 'GTO 3', 'S', 'C', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/sport/gto-3/', 324),
  ('Gin', 'GTO 3', 'M', 'C', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/sport/gto-3/', 325),
  ('Gin', 'GTO 3', 'L', 'C', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/sport/gto-3/', 326),
  ('Gin', 'GTO 3', 'XL', 'C', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/sport/gto-3/', 327),
  ('Gin', 'Leopard', 'XS', 'D', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/high-performance/leopard/', 328),
  ('Gin', 'Leopard', 'S', 'D', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/high-performance/leopard/', 329),
  ('Gin', 'Leopard', 'M', 'D', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/high-performance/leopard/', 330),
  ('Gin', 'Leopard', 'L', 'D', 'Paraglider', 'Current', 'https://www.gingliders.com/en/paragliders/high-performance/leopard/', 331),
  ('Gin', 'Puma', 'XS', 'D', 'Hike and fly performance', 'Current', 'https://www.gingliders.com/en/paragliders/high-performance/puma/', 332),
  ('Gin', 'Puma', 'S', 'D', 'Hike and fly performance', 'Current', 'https://www.gingliders.com/en/paragliders/high-performance/puma/', 333),
  ('Gin', 'Puma', 'M', 'D', 'Hike and fly performance', 'Current', 'https://www.gingliders.com/en/paragliders/high-performance/puma/', 334),
  ('Gin', 'Puma', 'L', 'D', 'Hike and fly performance', 'Current', 'https://www.gingliders.com/en/paragliders/high-performance/puma/', 335),
  ('Gin', 'Boomerang 12', 'S', 'CCC', 'Competition', 'Current', 'https://www.gingliders.com/en/paragliders/high-performance/boomerang-12/', 336),
  ('Gin', 'Boomerang 12', 'SM', 'CCC', 'Competition', 'Current', 'https://www.gingliders.com/en/paragliders/high-performance/boomerang-12/', 337),
  ('Gin', 'Boomerang 12', 'M', 'CCC', 'Competition', 'Current', 'https://www.gingliders.com/en/paragliders/high-performance/boomerang-12/', 338),
  ('Gin', 'Boomerang 12', 'ML', 'CCC', 'Competition', 'Current', 'https://www.gingliders.com/en/paragliders/high-performance/boomerang-12/', 339),
  ('Gin', 'Boomerang 12', 'L', 'CCC', 'Competition', 'Current', 'https://www.gingliders.com/en/paragliders/high-performance/boomerang-12/', 340),
  ('Gin', 'Boomerang 12', 'XL', 'CCC', 'Competition', 'Current', 'https://www.gingliders.com/en/paragliders/high-performance/boomerang-12/', 341),
  ('Gin', 'Fuse 4', '37', 'B', 'Tandem', 'Current', 'https://www.gingliders.com/en/paragliders/tandem/fuse-4/', 342),
  ('Gin', 'Fuse 4', '41', 'B', 'Tandem', 'Current', 'https://www.gingliders.com/en/paragliders/tandem/fuse-4/', 343),
  ('Gin', 'Fuse 4', '44', 'B', 'Tandem', 'Current', 'https://www.gingliders.com/en/paragliders/tandem/fuse-4/', 344),
  ('Gin', 'Fuse mini', '32', 'B', 'Small tandem', 'Current', 'https://www.gingliders.com/en/paragliders/tandem/fuse-mini/', 345),
  ('Gin', 'Fuse mini', '35', 'B', 'Small tandem', 'Current', 'https://www.gingliders.com/en/paragliders/tandem/fuse-mini/', 346),
  ('Gin', 'Yeti tandem 3', '37', 'A', 'Light tandem', 'Current', 'https://www.gingliders.com/en/paragliders/tandem/yeti-tandem-3/', 347),
  ('Gin', 'Yeti tandem 3', '41', 'B', 'Light tandem', 'Current', 'https://www.gingliders.com/en/paragliders/tandem/yeti-tandem-3/', 348),
  ('Gin', 'Griffin', '14', 'Uncertified', 'Miniwing', 'Current', 'https://www.gingliders.com/en/paragliders/mini-wings/griffin/', 349),
  ('Gin', 'Griffin', '16', 'C', 'Miniwing', 'Current', 'https://www.gingliders.com/en/paragliders/mini-wings/griffin/', 350),
  ('Gin', 'Griffin', '18', 'Uncertified', 'Miniwing', 'Current', 'https://www.gingliders.com/en/paragliders/mini-wings/griffin/', 351),
  ('Little Cloud', 'GT2', '20', 'EN 926-1', 'Paraglider', 'Current', 'https://littlecloud.fr/en/gt2-en/', 352),
  ('Little Cloud', 'GT2', '22', 'EN 926-1', 'Paraglider', 'Current', 'https://littlecloud.fr/en/gt2-en/', 353),
  ('Little Cloud', 'GT2', '24', 'B', 'Paraglider', 'Current', 'https://littlecloud.fr/en/gt2-en/', 354),
  ('Little Cloud', 'GT2', '26', 'EN 926-1', 'Paraglider', 'Current', 'https://littlecloud.fr/en/gt2-en/', 355),
  ('Little Cloud', 'GT2', '28', 'EN 926-1', 'Paraglider', 'Current', 'https://littlecloud.fr/en/gt2-en/', 356),
  ('Little Cloud', 'Gracchio Mk3', '20', 'Uncertified', 'Paraglider', 'Current', 'https://littlecloud.fr/en/gracchio-mk3-en/', 357),
  ('Little Cloud', 'Gracchio Mk3', '21', 'Uncertified', 'Paraglider', 'Current', 'https://littlecloud.fr/en/gracchio-mk3-en/', 358),
  ('Little Cloud', 'Gracchio Mk3', '22', 'Uncertified', 'Paraglider', 'Current', 'https://littlecloud.fr/en/gracchio-mk3-en/', 359),
  ('Little Cloud', 'Gracchio Mk3', '23', 'Uncertified', 'Paraglider', 'Current', 'https://littlecloud.fr/en/gracchio-mk3-en/', 360),
  ('Little Cloud', 'Gracchio Mk3', '24', 'Uncertified', 'Paraglider', 'Current', 'https://littlecloud.fr/en/gracchio-mk3-en/', 361),
  ('Little Cloud', 'Gracchio Mk3', '25', 'Uncertified', 'Paraglider', 'Current', 'https://littlecloud.fr/en/gracchio-mk3-en/', 362),
  ('Little Cloud', 'Gracchio Mk3', '27', 'Uncertified', 'Paraglider', 'Current', 'https://littlecloud.fr/en/gracchio-mk3-en/', 363),
  ('Little Cloud', 'Urubu Mk2', '20.5', 'Uncertified', 'Paraglider', 'Current', 'https://littlecloud.fr/en/urubu-mk2-en/', 364),
  ('Little Cloud', 'Urubu Mk2', '22', 'Uncertified', 'Paraglider', 'Current', 'https://littlecloud.fr/en/urubu-mk2-en/', 365),
  ('Little Cloud', 'Urubu Mk2', '23.5', 'Uncertified', 'Paraglider', 'Current', 'https://littlecloud.fr/en/urubu-mk2-en/', 366),
  ('Little Cloud', 'Urubu Mk2', '25', 'Uncertified', 'Paraglider', 'Current', 'https://littlecloud.fr/en/urubu-mk2-en/', 367),
  ('Little Cloud', 'Urubu Mk2', '26.5', 'Uncertified', 'Paraglider', 'Current', 'https://littlecloud.fr/en/urubu-mk2-en/', 368),
  ('Little Cloud', 'Urubu King', 'S', 'Uncertified', 'Paraglider', 'Recent previous', 'https://littlecloud.fr/en/urubu-king-en/', 369),
  ('Little Cloud', 'Urubu King', 'M', 'Uncertified', 'Paraglider', 'Recent previous', 'https://littlecloud.fr/en/urubu-king-en/', 370),
  ('Little Cloud', 'Urubu King', 'L', 'Uncertified', 'Paraglider', 'Recent previous', 'https://littlecloud.fr/en/urubu-king-en/', 371),
  ('Little Cloud', 'Puffin V2', '14', 'Uncertified', 'Miniwing', 'Current', 'https://littlecloud.fr/en/puffin-v2-en/', 372),
  ('Little Cloud', 'Puffin V2', '16', 'Uncertified', 'Miniwing', 'Current', 'https://littlecloud.fr/en/puffin-v2-en/', 373),
  ('Little Cloud', 'Puffin V2', '19', 'Uncertified', 'Miniwing', 'Current', 'https://littlecloud.fr/en/puffin-v2-en/', 374),
  ('Little Cloud', 'Bidule', 'S (31)', 'D', 'Tandem', 'Current', 'https://littlecloud.fr/en/bidule-en/', 375),
  ('Little Cloud', 'Bidule', 'XL (38)', 'C', 'Tandem', 'Current', 'https://littlecloud.fr/en/bidule-en/', 376),
  ('Little Cloud', 'SuperFly', '17', 'EN 926-1', 'Miniwing', 'Current', 'https://littlecloud.fr/en/superfly-en/', 377),
  ('Little Cloud', 'SuperFly', '19.5', 'EN 926-1', 'Miniwing', 'Current', 'https://littlecloud.fr/en/superfly-en/', 378),
  ('Little Cloud', 'SuperFly', '22.5', 'EN 926-1', 'Miniwing', 'Current', 'https://littlecloud.fr/en/superfly-en/', 379),
  ('Little Cloud', 'Kagoo2', '14', 'EN 926-1', 'Miniwing', 'Current', 'https://littlecloud.fr/en/kagoo2-en/', 380),
  ('Little Cloud', 'Kagoo2', '16', 'EN 926-1', 'Miniwing', 'Current', 'https://littlecloud.fr/en/kagoo2-en/', 381),
  ('Little Cloud', 'Kagoo2', '18', 'EN 926-1', 'Miniwing', 'Current', 'https://littlecloud.fr/en/kagoo2-en/', 382),
  ('Little Cloud', 'Kagoo2', '20', 'EN 926-1', 'Miniwing', 'Current', 'https://littlecloud.fr/en/kagoo2-en/', 383),
  ('Little Cloud', 'Kagoo2', '23', 'EN 926-1', 'Miniwing', 'Current', 'https://littlecloud.fr/en/kagoo2-en/', 384),
  ('Little Cloud', 'La Mouette', '14', 'Load test', 'Parakite', 'Current', 'https://littlecloud.fr/en/la-mouette-en/', 385),
  ('Little Cloud', 'La Mouette', '16', 'Load test', 'Parakite', 'Current', 'https://littlecloud.fr/en/la-mouette-en/', 386),
  ('Little Cloud', 'La Mouette', '19', 'Load test', 'Parakite', 'Current', 'https://littlecloud.fr/en/la-mouette-en/', 387),
  ('Little Cloud', 'La Mouette', '22', 'Load test', 'Parakite', 'Current', 'https://littlecloud.fr/en/la-mouette-en/', 388),
  ('Little Cloud', 'La Mouette', '25', 'Load test', 'Parakite', 'Current', 'https://littlecloud.fr/en/la-mouette-en/', 389),
  ('Little Cloud', 'The Spiruline Pro', '8', 'EN 926-1', 'Miniwing', 'Current', 'https://littlecloud.fr/en/the-spiruline-pro-en/', 390),
  ('Little Cloud', 'The Spiruline Pro', '10', 'EN 926-1', 'Miniwing', 'Current', 'https://littlecloud.fr/en/the-spiruline-pro-en/', 391),
  ('Little Cloud', 'The Spiruline Pro', '12', 'EN 926-1', 'Miniwing', 'Current', 'https://littlecloud.fr/en/the-spiruline-pro-en/', 392),
  ('Skywalk', 'MESCAL7', '75', 'A', 'Paraglider', 'Current', 'https://skywalk.info/project/mescal7/', 393),
  ('Skywalk', 'MESCAL7', '85', 'A', 'Paraglider', 'Current', 'https://skywalk.info/project/mescal7/', 394),
  ('Skywalk', 'MESCAL7', '95', 'A', 'Paraglider', 'Current', 'https://skywalk.info/project/mescal7/', 395),
  ('Skywalk', 'MESCAL7', '105', 'A', 'Paraglider', 'Current', 'https://skywalk.info/project/mescal7/', 396),
  ('Skywalk', 'MESCAL7', '115', 'A', 'Paraglider', 'Current', 'https://skywalk.info/project/mescal7/', 397),
  ('Skywalk', 'MESCAL7', '135', 'A', 'Paraglider', 'Current', 'https://skywalk.info/project/mescal7/', 398),
  ('Skywalk', 'TEQUILA6', '75', 'B', 'Paraglider', 'Current', 'https://skywalk.info/project/tequila6/', 399),
  ('Skywalk', 'TEQUILA6', '85', 'B', 'Paraglider', 'Current', 'https://skywalk.info/project/tequila6/', 400),
  ('Skywalk', 'TEQUILA6', '95', 'B', 'Paraglider', 'Current', 'https://skywalk.info/project/tequila6/', 401),
  ('Skywalk', 'TEQUILA6', '105', 'B', 'Paraglider', 'Current', 'https://skywalk.info/project/tequila6/', 402),
  ('Skywalk', 'TEQUILA6', '115', 'B', 'Paraglider', 'Current', 'https://skywalk.info/project/tequila6/', 403),
  ('Skywalk', 'TEQUILA6', '135', 'B', 'Paraglider', 'Current', 'https://skywalk.info/project/tequila6/', 404),
  ('Skywalk', 'ARAK2', '75', 'B', 'Paraglider', 'Current', 'https://skywalk.info/project/arak2/', 405),
  ('Skywalk', 'ARAK2', '85', 'B', 'Paraglider', 'Current', 'https://skywalk.info/project/arak2/', 406),
  ('Skywalk', 'ARAK2', '95', 'B', 'Paraglider', 'Current', 'https://skywalk.info/project/arak2/', 407),
  ('Skywalk', 'ARAK2', '105', 'B', 'Paraglider', 'Current', 'https://skywalk.info/project/arak2/', 408),
  ('Skywalk', 'ARAK2', '115', 'B', 'Paraglider', 'Current', 'https://skywalk.info/project/arak2/', 409),
  ('Skywalk', 'ARAK2', '135', 'B', 'Paraglider', 'Current', 'https://skywalk.info/project/arak2/', 410),
  ('Skywalk', 'CHILI5', '75', 'B', 'Paraglider', 'Current', 'https://skywalk.info/project/chili5/', 411),
  ('Skywalk', 'CHILI5', '85', 'B', 'Paraglider', 'Current', 'https://skywalk.info/project/chili5/', 412),
  ('Skywalk', 'CHILI5', '95', 'B', 'Paraglider', 'Current', 'https://skywalk.info/project/chili5/', 413),
  ('Skywalk', 'CHILI5', '105', 'B', 'Paraglider', 'Current', 'https://skywalk.info/project/chili5/', 414),
  ('Skywalk', 'CHILI5', '115', 'B', 'Paraglider', 'Current', 'https://skywalk.info/project/chili5/', 415),
  ('Skywalk', 'CHILI5', '135', 'B', 'Paraglider', 'Current', 'https://skywalk.info/project/chili5/', 416),
  ('Skywalk', 'MINT', '75', 'C', 'Paraglider', 'Current', 'https://skywalk.info/project/mint/', 417),
  ('Skywalk', 'MINT', '85', 'C', 'Paraglider', 'Current', 'https://skywalk.info/project/mint/', 418),
  ('Skywalk', 'MINT', '95', 'C', 'Paraglider', 'Current', 'https://skywalk.info/project/mint/', 419),
  ('Skywalk', 'MINT', '105', 'C', 'Paraglider', 'Current', 'https://skywalk.info/project/mint/', 420),
  ('Skywalk', 'MINT', '115', 'C', 'Paraglider', 'Current', 'https://skywalk.info/project/mint/', 421),
  ('Skywalk', 'MINT', '125', 'C', 'Paraglider', 'Current', 'https://skywalk.info/project/mint/', 422),
  ('Skywalk', 'MASALA4', '70+', 'A', 'Hike and fly', 'Current', 'https://skywalk.info/project/masala4/', 423),
  ('Skywalk', 'MASALA4', '80+', 'A', 'Hike and fly', 'Current', 'https://skywalk.info/project/masala4/', 424),
  ('Skywalk', 'MASALA4', '95+', 'A', 'Hike and fly', 'Current', 'https://skywalk.info/project/masala4/', 425),
  ('Skywalk', 'MASALA4', '105+', 'A', 'Hike and fly', 'Current', 'https://skywalk.info/project/masala4/', 426),
  ('Skywalk', 'MASALA4', '120', 'A', 'Hike and fly', 'Current', 'https://skywalk.info/project/masala4/', 427),
  ('Skywalk', 'ARAK AIR2', '70+', 'B', 'Hike and fly', 'Current', 'https://skywalk.info/project/arak-air2/', 428),
  ('Skywalk', 'ARAK AIR2', '80+', 'B', 'Hike and fly', 'Current', 'https://skywalk.info/project/arak-air2/', 429),
  ('Skywalk', 'ARAK AIR2', '95+', 'B', 'Hike and fly', 'Current', 'https://skywalk.info/project/arak-air2/', 430),
  ('Skywalk', 'ARAK AIR2', '105+', 'B', 'Hike and fly', 'Current', 'https://skywalk.info/project/arak-air2/', 431),
  ('Skywalk', 'ARAK AIR2', '115+', 'B', 'Hike and fly', 'Current', 'https://skywalk.info/project/arak-air2/', 432),
  ('Skywalk', 'CUMEO2', '70+', 'B', 'Hike and fly', 'Current', 'https://skywalk.info/project/cumeo2/', 433),
  ('Skywalk', 'CUMEO2', '80+', 'B', 'Hike and fly', 'Current', 'https://skywalk.info/project/cumeo2/', 434),
  ('Skywalk', 'CUMEO2', '95+', 'B', 'Hike and fly', 'Current', 'https://skywalk.info/project/cumeo2/', 435),
  ('Skywalk', 'CUMEO2', '105+', 'B', 'Hike and fly', 'Current', 'https://skywalk.info/project/cumeo2/', 436),
  ('Skywalk', 'CUMEO2', '115+', 'B', 'Hike and fly', 'Current', 'https://skywalk.info/project/cumeo2/', 437),
  ('Skywalk', 'SAGE', '75+', 'C', 'Hike and fly', 'Current', 'https://skywalk.info/project/sage/', 438),
  ('Skywalk', 'SAGE', '85+', 'C', 'Hike and fly', 'Current', 'https://skywalk.info/project/sage/', 439),
  ('Skywalk', 'SAGE', '95+', 'C', 'Hike and fly', 'Current', 'https://skywalk.info/project/sage/', 440),
  ('Skywalk', 'SAGE', '105+', 'C', 'Hike and fly', 'Current', 'https://skywalk.info/project/sage/', 441),
  ('Skywalk', 'SAGE', '115+', 'C', 'Hike and fly', 'Current', 'https://skywalk.info/project/sage/', 442),
  ('Skywalk', 'X-ALPS6', '75+', 'D', 'Hike and fly competition', 'Current', 'https://skywalk.info/project/x-alps6/', 443),
  ('Skywalk', 'X-ALPS6', '85+', 'D', 'Hike and fly competition', 'Current', 'https://skywalk.info/project/x-alps6/', 444),
  ('Skywalk', 'X-ALPS6', '95+', 'D', 'Hike and fly competition', 'Current', 'https://skywalk.info/project/x-alps6/', 445),
  ('Skywalk', 'X-ALPS6', '105+', 'D', 'Hike and fly competition', 'Current', 'https://skywalk.info/project/x-alps6/', 446),
  ('Skywalk', 'SPIRIT', '75+', 'C', 'Miniwing', 'Current', 'https://skywalk.info/project/spirit/', 447),
  ('Skywalk', 'SPIRIT', '85+', 'B/C', 'Miniwing', 'Current', 'https://skywalk.info/project/spirit/', 448),
  ('Skywalk', 'SPIRIT', '105+', 'A/B/C', 'Miniwing', 'Current', 'https://skywalk.info/project/spirit/', 449),
  ('Skywalk', 'SPIRIT', '120', 'A/B', 'Miniwing', 'Current', 'https://skywalk.info/project/spirit/', 450),
  ('Skywalk', 'TONIC2', 'XS', 'C', 'Miniwing', 'Current', 'https://skywalk.info/project/tonic2/', 451),
  ('Skywalk', 'TONIC2', 'S', 'B/C', 'Miniwing', 'Current', 'https://skywalk.info/project/tonic2/', 452),
  ('Skywalk', 'TONIC2', 'M', 'B/C', 'Miniwing', 'Current', 'https://skywalk.info/project/tonic2/', 453),
  ('Skywalk', 'PACE', '70+', 'B', 'Single surface', 'Current', 'https://skywalk.info/project/pace/', 454),
  ('Skywalk', 'PACE', '85+', 'B', 'Single surface', 'Current', 'https://skywalk.info/project/pace/', 455),
  ('Skywalk', 'PACE', '95+', 'B', 'Single surface', 'Current', 'https://skywalk.info/project/pace/', 456),
  ('Skywalk', 'JOIN''T5', '200', 'B', 'Tandem', 'Current', 'https://skywalk.info/project/joint5/', 457),
  ('Skywalk', 'JOIN''T5', '220', 'B', 'Tandem', 'Current', 'https://skywalk.info/project/joint5/', 458),
  ('Skywalk', 'JOIN''T5', '240', 'B', 'Tandem', 'Current', 'https://skywalk.info/project/joint5/', 459),
  ('Nova', 'NIVO', 'XXS', 'A', 'Paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/nivo/', 460),
  ('Nova', 'NIVO', 'XS', 'A', 'Paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/nivo/', 461),
  ('Nova', 'NIVO', 'S', 'A', 'Paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/nivo/', 462),
  ('Nova', 'NIVO', 'M', 'A', 'Paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/nivo/', 463),
  ('Nova', 'NIVO', 'L', 'A', 'Paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/nivo/', 464),
  ('Nova', 'NIVO', 'XL', 'A', 'Paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/nivo/', 465),
  ('Nova', 'DOUBLESKIN 2', '16', 'A', 'Single surface', 'Recent previous', 'https://www.nova.eu/en/gliders/doubleskin-2/', 466),
  ('Nova', 'DOUBLESKIN 2', '18', 'A', 'Single surface', 'Recent previous', 'https://www.nova.eu/en/gliders/doubleskin-2/', 467),
  ('Nova', 'DOUBLESKIN 2', '20', 'A', 'Single surface', 'Recent previous', 'https://www.nova.eu/en/gliders/doubleskin-2/', 468),
  ('Nova', 'AONIC 2', 'XXXS', 'A', 'Paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/aonic-2/', 469),
  ('Nova', 'AONIC 2', 'XXS', 'A', 'Paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/aonic-2/', 470),
  ('Nova', 'AONIC 2', 'XS', 'A', 'Paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/aonic-2/', 471),
  ('Nova', 'AONIC 2', 'S', 'A', 'Paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/aonic-2/', 472),
  ('Nova', 'AONIC 2', 'M', 'A', 'Paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/aonic-2/', 473),
  ('Nova', 'AONIC 2', 'L', 'A', 'Paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/aonic-2/', 474),
  ('Nova', 'NEXO', 'XXS', 'B', 'Paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/nexo/', 475),
  ('Nova', 'NEXO', 'XS', 'B', 'Paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/nexo/', 476),
  ('Nova', 'NEXO', 'S', 'B', 'Paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/nexo/', 477),
  ('Nova', 'NEXO', 'M', 'B', 'Paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/nexo/', 478),
  ('Nova', 'NEXO', 'L', 'B', 'Paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/nexo/', 479),
  ('Nova', 'ION 7 Light', 'XXXS', 'B', 'Light paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/ion-7-light/', 480),
  ('Nova', 'ION 7 Light', 'XXS', 'B', 'Light paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/ion-7-light/', 481),
  ('Nova', 'ION 7 Light', 'XS', 'B', 'Light paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/ion-7-light/', 482),
  ('Nova', 'ION 7 Light', 'S', 'B', 'Light paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/ion-7-light/', 483),
  ('Nova', 'ION 7 Light', 'M', 'B', 'Light paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/ion-7-light/', 484),
  ('Nova', 'ION 7 Light', 'L', 'B', 'Light paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/ion-7-light/', 485),
  ('Nova', 'MENTOR 7', 'XS', 'B', 'Paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/mentor-7/', 486),
  ('Nova', 'MENTOR 7', 'S', 'B', 'Paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/mentor-7/', 487),
  ('Nova', 'MENTOR 7', 'M', 'B', 'Paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/mentor-7/', 488),
  ('Nova', 'MENTOR 7 Light', 'XXS', 'B', 'Light paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/mentor-7-light/', 489),
  ('Nova', 'MENTOR 7 Light', 'XS', 'B', 'Light paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/mentor-7-light/', 490),
  ('Nova', 'MENTOR 7 Light', 'S', 'B', 'Light paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/mentor-7-light/', 491),
  ('Nova', 'MENTOR 7 Light', 'M', 'B', 'Light paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/mentor-7-light/', 492),
  ('Nova', 'MENTOR 7 Light', 'L', 'B', 'Light paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/mentor-7-light/', 493),
  ('Nova', 'CODEX', 'XXS', 'C', 'Paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/codex/', 494),
  ('Nova', 'CODEX', 'XS', 'C', 'Paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/codex/', 495),
  ('Nova', 'CODEX', 'S', 'C', 'Paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/codex/', 496),
  ('Nova', 'CODEX', 'M', 'C', 'Paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/codex/', 497),
  ('Nova', 'CODEX', 'L', 'C', 'Paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/codex/', 498),
  ('Nova', 'VORTEX', 'XXXS', 'C', 'Light paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/vortex/', 499),
  ('Nova', 'VORTEX', 'XXS', 'C', 'Light paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/vortex/', 500),
  ('Nova', 'VORTEX', 'XS', 'C', 'Light paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/vortex/', 501),
  ('Nova', 'VORTEX', 'S', 'C', 'Light paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/vortex/', 502),
  ('Nova', 'VORTEX', 'M', 'C', 'Light paraglider', 'Recent previous', 'https://www.nova.eu/en/gliders/vortex/', 503),
  ('Nova', 'XENON 3', 'XS', 'D', 'Light performance', 'Recent previous', 'https://www.nova.eu/en/gliders/xenon-3/', 504),
  ('Nova', 'XENON 3', 'S', 'D', 'Light performance', 'Recent previous', 'https://www.nova.eu/en/gliders/xenon-3/', 505),
  ('Nova', 'XENON 3', 'M', 'D', 'Light performance', 'Recent previous', 'https://www.nova.eu/en/gliders/xenon-3/', 506),
  ('Nova', 'XENON 3', 'L', 'D', 'Light performance', 'Recent previous', 'https://www.nova.eu/en/gliders/xenon-3/', 507),
  ('Nova', 'BANTAM 2', '12', 'D', 'Miniwing', 'Recent previous', 'https://www.nova.eu/en/gliders/bantam-2/', 508),
  ('Nova', 'BANTAM 2', '14', 'D', 'Miniwing', 'Recent previous', 'https://www.nova.eu/en/gliders/bantam-2/', 509),
  ('Nova', 'BANTAM 2', '16', 'D', 'Miniwing', 'Recent previous', 'https://www.nova.eu/en/gliders/bantam-2/', 510),
  ('Nova', 'BION 3', 'L', 'B', 'Tandem', 'Recent previous', 'https://www.nova.eu/en/gliders/bion-3/', 511),
  ('Nova', 'GLITCH', '18', 'Load test', 'Acro', 'Recent previous', 'https://www.nova.eu/en/gliders/glitch/', 512),
  ('Nova', 'GLITCH', '20', 'Load test', 'Acro', 'Recent previous', 'https://www.nova.eu/en/gliders/glitch/', 513),
  ('Nova', 'GLITCH', '22', 'Load test', 'Acro', 'Recent previous', 'https://www.nova.eu/en/gliders/glitch/', 514),
  ('PHI', 'FANTASIA', '18', 'A', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 515),
  ('PHI', 'FANTASIA', '20', 'A', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 516),
  ('PHI', 'FANTASIA', '22', 'A', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 517),
  ('PHI', 'FANTASIA', '24', 'A', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 518),
  ('PHI', 'FANTASIA', '26', 'A', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 519),
  ('PHI', 'SOLA', '18', 'A', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 520),
  ('PHI', 'SOLA', '20', 'A', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 521),
  ('PHI', 'SOLA', '22', 'A', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 522),
  ('PHI', 'SOLA', '24', 'A', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 523),
  ('PHI', 'SOLA', '26', 'A', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 524),
  ('PHI', 'SOLA GT', '18', 'A', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 525),
  ('PHI', 'SOLA GT', '20', 'A', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 526),
  ('PHI', 'SOLA GT', '22', 'A', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 527),
  ('PHI', 'SOLA GT', '24', 'A', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 528),
  ('PHI', 'SOLA GT', '26', 'A', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 529),
  ('PHI', 'SOLA UL', '12', 'D', 'Hike and fly and miniwing', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 530),
  ('PHI', 'SOLA UL', '14', 'D', 'Hike and fly and miniwing', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 531),
  ('PHI', 'SOLA UL', '16', 'C', 'Hike and fly and miniwing', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 532),
  ('PHI', 'SOLA UL', '19', 'A', 'Hike and fly and miniwing', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 533),
  ('PHI', 'SONATA 2', '18', 'A', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 534),
  ('PHI', 'SONATA 2', '20', 'A', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 535),
  ('PHI', 'SONATA 2', '22', 'A', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 536),
  ('PHI', 'SONATA 2', '24', 'A', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 537),
  ('PHI', 'SONATA 2', '26', 'A', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 538),
  ('PHI', 'VIOLA 2', '16', 'A', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 539),
  ('PHI', 'VIOLA 2', '18', 'A', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 540),
  ('PHI', 'VIOLA 2', '20', 'A', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 541),
  ('PHI', 'VIOLA 2', '22', 'A', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 542),
  ('PHI', 'VIOLA 2', '24', 'A', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 543),
  ('PHI', 'VIOLA 2', '26', 'A', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 544),
  ('PHI', 'SYMPHONIA 2', '18', 'A', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 545),
  ('PHI', 'SYMPHONIA 2', '20', 'A', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 546),
  ('PHI', 'SYMPHONIA 2', '22', 'A', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 547),
  ('PHI', 'SYMPHONIA 2', '23', 'A', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 548),
  ('PHI', 'SYMPHONIA 2', '24', 'A', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 549),
  ('PHI', 'SYMPHONIA 2', '26', 'A', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 550),
  ('PHI', 'SYMPHONIA 2 light', '18', 'A', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 551),
  ('PHI', 'SYMPHONIA 2 light', '20', 'A', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 552),
  ('PHI', 'SYMPHONIA 2 light', '22', 'A', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 553),
  ('PHI', 'SYMPHONIA 2 light', '23', 'A', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 554),
  ('PHI', 'SYMPHONIA 2 light', '24', 'A', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 555),
  ('PHI', 'SYMPHONIA 2 light', '26', 'A', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 556),
  ('PHI', 'TENOR 2', '17', 'B', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 557),
  ('PHI', 'TENOR 2', '19', 'B', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 558),
  ('PHI', 'TENOR 2', '21', 'B', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 559),
  ('PHI', 'TENOR 2', '22', 'B', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 560),
  ('PHI', 'TENOR 2', '23', 'B', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 561),
  ('PHI', 'TENOR 2', '25', 'B', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 562),
  ('PHI', 'TENOR 2 light', '17', 'B', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 563),
  ('PHI', 'TENOR 2 light', '19', 'B', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 564),
  ('PHI', 'TENOR 2 light', '21', 'B', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 565),
  ('PHI', 'TENOR 2 light', '22', 'B', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 566),
  ('PHI', 'TENOR 2 light', '23', 'B', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 567),
  ('PHI', 'TENOR 2 light', '25', 'B', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 568),
  ('PHI', 'BEAT 2', '18', 'B', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 569),
  ('PHI', 'BEAT 2', '20', 'B', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 570),
  ('PHI', 'BEAT 2', '22', 'B', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 571),
  ('PHI', 'BEAT 2', '23', 'B', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 572),
  ('PHI', 'BEAT 2', '24', 'B', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 573),
  ('PHI', 'BEAT 2', '26', 'B', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 574),
  ('PHI', 'BEAT 2 light', '18', 'B', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 575),
  ('PHI', 'BEAT 2 light', '20', 'B', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 576),
  ('PHI', 'BEAT 2 light', '22', 'B', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 577),
  ('PHI', 'BEAT 2 light', '23', 'B', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 578),
  ('PHI', 'BEAT 2 light', '24', 'B', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 579),
  ('PHI', 'BEAT 2 light', '26', 'B', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 580),
  ('PHI', 'BEAT 2 light', '28', 'B', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 581),
  ('PHI', 'MAESTRO 3', '19', 'B', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 582),
  ('PHI', 'MAESTRO 3', '21', 'B', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 583),
  ('PHI', 'MAESTRO 3', '22', 'B', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 584),
  ('PHI', 'MAESTRO 3', '23', 'B', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 585),
  ('PHI', 'MAESTRO 3 light', '17', 'B', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 586),
  ('PHI', 'MAESTRO 3 light', '18', 'B', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 587),
  ('PHI', 'MAESTRO 3 light', '19', 'B', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 588),
  ('PHI', 'MAESTRO 3 light', '21', 'B', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 589),
  ('PHI', 'MAESTRO 3 light', '22', 'B', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 590),
  ('PHI', 'MAESTRO 3 light', '23', 'B', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 591),
  ('PHI', 'MAESTRO 3 light', '24', 'B', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 592),
  ('PHI', 'MAESTRO 3 light', '25', 'B', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 593),
  ('PHI', 'MAESTRO 2 light', '17', 'B', 'Light paraglider', 'Recent previous', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 594),
  ('PHI', 'MAESTRO 2 light', '18', 'B', 'Light paraglider', 'Recent previous', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 595),
  ('PHI', 'MAESTRO 2 light', '19', 'B', 'Light paraglider', 'Recent previous', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 596),
  ('PHI', 'MAESTRO 2 light', '21', 'B', 'Light paraglider', 'Recent previous', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 597),
  ('PHI', 'MAESTRO 2 light', '22', 'B', 'Light paraglider', 'Recent previous', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 598),
  ('PHI', 'MAESTRO 2 light', '23', 'B', 'Light paraglider', 'Recent previous', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 599),
  ('PHI', 'MAESTRO 2 light', '25', 'B', 'Light paraglider', 'Recent previous', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 600),
  ('PHI', 'ALLEGRO', '19', 'C', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 601),
  ('PHI', 'ALLEGRO', '20', 'C', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 602),
  ('PHI', 'ALLEGRO', '21', 'C', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 603),
  ('PHI', 'ALLEGRO', '22', 'C', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 604),
  ('PHI', 'ALLEGRO', '24', 'C', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 605),
  ('PHI', 'ALLEGRO light', '17', 'C', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 606),
  ('PHI', 'ALLEGRO light', '19', 'C', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 607),
  ('PHI', 'ALLEGRO light', '20', 'C', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 608),
  ('PHI', 'ALLEGRO light', '21', 'C', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 609),
  ('PHI', 'ALLEGRO light', '22', 'C', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 610),
  ('PHI', 'ALLEGRO light', '24', 'C', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 611),
  ('PHI', 'SCALA 2', '18', 'C', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 612),
  ('PHI', 'SCALA 2', '19', 'C', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 613),
  ('PHI', 'SCALA 2', '20', 'C', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 614),
  ('PHI', 'SCALA 2', '21', 'C', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 615),
  ('PHI', 'SCALA 2', '23', 'C', 'Paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 616),
  ('PHI', 'SCALA 2 light', '18', 'C', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 617),
  ('PHI', 'SCALA 2 light', '19', 'C', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 618),
  ('PHI', 'SCALA 2 light', '20', 'C', 'Light paraglider', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 619),
  ('PHI', 'CONCERTO', '36', 'A', 'Tandem', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 620),
  ('PHI', 'RONDO', '190', 'B', 'Tandem', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 621),
  ('PHI', 'RONDO', '210', 'B', 'Tandem', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 622),
  ('PHI', 'RONDO', '230', 'B', 'Tandem', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 623),
  ('PHI', 'RONDO C', '190', 'B', 'Tandem', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 624),
  ('PHI', 'RONDO C', '210', 'B', 'Tandem', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 625),
  ('PHI', 'RONDO C', '230', 'B', 'Tandem', 'Current', 'https://phi-air.com/wp-content/uploads/2025/10/PHI-Techdata-Eng.pdf', 626),
  ('Mac Para', 'Progress 2', '23 (XS)', 'A', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/progress-2', 627),
  ('Mac Para', 'Progress 2', '25 (S)', 'A', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/progress-2', 628),
  ('Mac Para', 'Progress 2', '27 (M)', 'A', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/progress-2', 629),
  ('Mac Para', 'Progress 2', '30 (L)', 'A', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/progress-2', 630),
  ('Mac Para', 'Progress 2', '33 (XL)', 'A', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/progress-2', 631),
  ('Mac Para', 'Muse 5', '22 (XS)', 'A', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/muse-5', 632),
  ('Mac Para', 'Muse 5', '25 (S)', 'A', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/muse-5', 633),
  ('Mac Para', 'Muse 5', '27 (M)', 'A', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/muse-5', 634),
  ('Mac Para', 'Muse 5', '29 (L)', 'A', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/muse-5', 635),
  ('Mac Para', 'Muse 5', '31 (XL)', 'A', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/muse-5', 636),
  ('Mac Para', 'Muse 5', '34 (XXL)', 'A', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/muse-5', 637),
  ('Mac Para', 'Aravis', '17 (XXS)', 'A', 'Hike and fly', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/aravis', 638),
  ('Mac Para', 'Aravis', '19 (XS)', 'A', 'Hike and fly', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/aravis', 639),
  ('Mac Para', 'Aravis', '21 (S)', 'A', 'Hike and fly', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/aravis', 640),
  ('Mac Para', 'Aravis', '23 (M)', 'A', 'Hike and fly', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/aravis', 641),
  ('Mac Para', 'Aravis', '25 (L)', 'A', 'Hike and fly', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/aravis', 642),
  ('Mac Para', 'Aravis', '28 (XL)', 'A', 'Hike and fly', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/aravis', 643),
  ('Mac Para', 'Illusion 2', '22 (XS)', 'B', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/illusion-2', 644),
  ('Mac Para', 'Illusion 2', '24 (S)', 'B', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/illusion-2', 645),
  ('Mac Para', 'Illusion 2', '26 (M)', 'B', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/illusion-2', 646),
  ('Mac Para', 'Illusion 2', '28 (L)', 'B', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/illusion-2', 647),
  ('Mac Para', 'Illusion 2', '30 (XL)', 'B', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/illusion-2', 648),
  ('Mac Para', 'Illusion 2', '33 (XXL)', 'B', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/illusion-2', 649),
  ('Mac Para', 'Eden 8', '21 (XS)', 'B', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/eden-8', 650),
  ('Mac Para', 'Eden 8', '23 (S)', 'B', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/eden-8', 651),
  ('Mac Para', 'Eden 8', '26 (M)', 'B', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/eden-8', 652),
  ('Mac Para', 'Eden 8', '28 (L)', 'B', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/eden-8', 653),
  ('Mac Para', 'Eden 8', '30 (XL)', 'B', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/eden-8', 654),
  ('Mac Para', 'Eden 8', '33 (XXL)', 'B', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/eden-8', 655),
  ('Mac Para', 'Elan 3', '22 (XS)', 'C', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/elan-3', 656),
  ('Mac Para', 'Elan 3', '24 (S)', 'C', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/elan-3', 657),
  ('Mac Para', 'Elan 3', '26 (M)', 'C', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/elan-3', 658),
  ('Mac Para', 'Elan 3', '28 (L)', 'C', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/elan-3', 659),
  ('Mac Para', 'Elan 3', '30 (XL)', 'C', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/elan-3', 660),
  ('Mac Para', 'Elan 3', '33 (XXL)', 'C', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/elan-3', 661),
  ('Mac Para', 'Verve', '21 (S)', 'C', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/verve', 662),
  ('Mac Para', 'Verve', '23 (M)', 'C', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/verve', 663),
  ('Mac Para', 'Verve', '25 (L)', 'C', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/verve', 664),
  ('Mac Para', 'Verve', '27 (XL)', 'C', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/verve', 665),
  ('Mac Para', 'Verve', '30 (XXL)', 'C', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/verve', 666),
  ('Mac Para', 'Elixir', '22 (S)', 'Pending', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/elixir', 667),
  ('Mac Para', 'Elixir', '24 (M)', 'C', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/elixir', 668),
  ('Mac Para', 'Elixir', '26 (L)', 'C', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/elixir', 669),
  ('Mac Para', 'Elixir', '29 (XL)', 'Pending', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/elixir', 670),
  ('Mac Para', 'Magus', '22 (S)', 'D', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/magus', 671),
  ('Mac Para', 'Magus', '24 (M)', 'D', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/magus', 672),
  ('Mac Para', 'Magus', '26 (L)', 'D', 'Paraglider', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/magus', 673),
  ('Mac Para', 'Pasha 7', '39 (M)', 'B', 'Tandem', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/pasha-7', 674),
  ('Mac Para', 'Pasha 7', '42 (L)', 'B', 'Tandem', 'Current', 'https://www.macpara.com/en/paragliders/free-flying/pasha-7', 675),
  ('Flow', 'Future 2', 'XS', 'A', 'Paraglider', 'Current', 'https://www.flowparagliders.com.au/future-2', 676),
  ('Flow', 'Future 2', 'S', 'A', 'Paraglider', 'Current', 'https://www.flowparagliders.com.au/future-2', 677),
  ('Flow', 'Future 2', 'M', 'A', 'Paraglider', 'Current', 'https://www.flowparagliders.com.au/future-2', 678),
  ('Flow', 'Future 2', 'L', 'A', 'Paraglider', 'Current', 'https://www.flowparagliders.com.au/future-2', 679),
  ('Flow', 'Cosmos 2', 'XXS', 'B', 'Paraglider', 'Current', 'https://www.flowparagliders.com.au/cosmos-2', 680),
  ('Flow', 'Cosmos 2', 'XS', 'B', 'Paraglider', 'Current', 'https://www.flowparagliders.com.au/cosmos-2', 681),
  ('Flow', 'Cosmos 2', 'S', 'B', 'Paraglider', 'Current', 'https://www.flowparagliders.com.au/cosmos-2', 682),
  ('Flow', 'Cosmos 2', 'M', 'B', 'Paraglider', 'Current', 'https://www.flowparagliders.com.au/cosmos-2', 683),
  ('Flow', 'Cosmos 2', 'L', 'B', 'Paraglider', 'Current', 'https://www.flowparagliders.com.au/cosmos-2', 684),
  ('Flow', 'Freedom 2', 'XS', 'B', 'Paraglider', 'Current', 'https://www.flowparagliders.com.au/freedom-2', 685),
  ('Flow', 'Freedom 2', 'S', 'B', 'Paraglider', 'Current', 'https://www.flowparagliders.com.au/freedom-2', 686),
  ('Flow', 'Freedom 2', 'M', 'B', 'Paraglider', 'Current', 'https://www.flowparagliders.com.au/freedom-2', 687),
  ('Flow', 'Freedom 2', 'L', 'B', 'Paraglider', 'Current', 'https://www.flowparagliders.com.au/freedom-2', 688),
  ('Flow', 'F2 Light', 'XS', 'B', 'Light paraglider', 'Current', 'https://www.flowparagliders.com.au/f2-light', 689),
  ('Flow', 'F2 Light', 'S', 'B', 'Light paraglider', 'Current', 'https://www.flowparagliders.com.au/f2-light', 690),
  ('Flow', 'F2 Light', 'M', 'B', 'Light paraglider', 'Current', 'https://www.flowparagliders.com.au/f2-light', 691),
  ('Flow', 'F2 Light', 'L', 'B', 'Light paraglider', 'Current', 'https://www.flowparagliders.com.au/f2-light', 692),
  ('Flow', 'Panorama 2', '32', 'EN 926-1', 'Tandem', 'Current', 'https://www.flowparagliders.com.au/panorama-2', 693),
  ('Flow', 'Panorama 2', '39', 'B', 'Tandem', 'Current', 'https://www.flowparagliders.com.au/panorama-2', 694),
  ('Flow', 'Panorama 2', '41', 'B', 'Tandem', 'Current', 'https://www.flowparagliders.com.au/panorama-2', 695),
  ('Flow', 'Mystic+', 'XS', 'C', 'Paraglider', 'Current', 'https://www.flowparagliders.com.au/mystic-plus', 696),
  ('Flow', 'Mystic+', 'M', 'C', 'Paraglider', 'Current', 'https://www.flowparagliders.com.au/mystic-plus', 697),
  ('Flow', 'Mystic+', 'L', 'C', 'Paraglider', 'Current', 'https://www.flowparagliders.com.au/mystic-plus', 698),
  ('Flow', 'Mystic', 'S', 'C', 'Paraglider', 'Recent previous', 'https://www.flowparagliders.com.au/mystic', 699),
  ('Flow', 'Fusion', 'S', 'C', 'Paraglider', 'Current', 'https://www.flowparagliders.com.au/fusion', 700),
  ('Flow', 'Fusion', 'M', 'C', 'Paraglider', 'Current', 'https://www.flowparagliders.com.au/fusion', 701),
  ('Flow', 'Fusion', 'ML', 'C', 'Paraglider', 'Current', 'https://www.flowparagliders.com.au/fusion', 702),
  ('Flow', 'Fusion', 'L', 'C', 'Paraglider', 'Current', 'https://www.flowparagliders.com.au/fusion', 703),
  ('Flow', 'Fusion Light', 'S', 'C', 'Light paraglider', 'Current', 'https://www.flowparagliders.com.au/fusion-light', 704),
  ('Flow', 'Fusion Light', 'M', 'C', 'Light paraglider', 'Current', 'https://www.flowparagliders.com.au/fusion-light', 705),
  ('Flow', 'Fusion Light', 'ML', 'C', 'Light paraglider', 'Current', 'https://www.flowparagliders.com.au/fusion-light', 706),
  ('Flow', 'XCRacer 2', 'S', 'D', 'Paraglider', 'Current', 'https://www.flowparagliders.com.au/xcracer-2', 707),
  ('Flow', 'XCRacer 2', 'M', 'D', 'Paraglider', 'Current', 'https://www.flowparagliders.com.au/xcracer-2', 708),
  ('Flow', 'XCRacer 2', 'ML', 'D', 'Paraglider', 'Current', 'https://www.flowparagliders.com.au/xcracer-2', 709),
  ('Flow', 'XCRacer 2', 'L', 'D', 'Paraglider', 'Current', 'https://www.flowparagliders.com.au/xcracer-2', 710),
  ('Flow', 'Spectra 2', 'XS', 'CCC', 'Competition', 'Current', 'https://www.flowparagliders.com.au/spectra-2', 711),
  ('Flow', 'Spectra 2', 'S', 'CCC', 'Competition', 'Current', 'https://www.flowparagliders.com.au/spectra-2', 712),
  ('Flow', 'Spectra 2', 'M', 'CCC', 'Competition', 'Current', 'https://www.flowparagliders.com.au/spectra-2', 713),
  ('Flow', 'Spectra 2', 'ML', 'CCC', 'Competition', 'Current', 'https://www.flowparagliders.com.au/spectra-2', 714),
  ('Flow', 'Spectra 2', 'L', 'CCC', 'Competition', 'Current', 'https://www.flowparagliders.com.au/spectra-2', 715),
  ('Flow', 'Spectra 2', 'XL', 'CCC', 'Competition', 'Current', 'https://www.flowparagliders.com.au/spectra-2', 716),
  ('Flow', 'Yoti 3', '15', 'EN 926-1', 'Miniwing', 'Current', 'https://www.flowparagliders.com.au/yoti-3', 717),
  ('Flow', 'Yoti 3', '17', 'EN 926-1', 'Miniwing', 'Current', 'https://www.flowparagliders.com.au/yoti-3', 718),
  ('Flow', 'Yoti 3', '19', 'EN 926-1', 'Miniwing', 'Current', 'https://www.flowparagliders.com.au/yoti-3', 719),
  ('Flow', 'Yoti 3', '21', 'EN 926-1', 'Miniwing', 'Current', 'https://www.flowparagliders.com.au/yoti-3', 720),
  ('Flow', 'Yoti 3 Light', '15', 'EN 926-1', 'Light miniwing', 'Current', 'https://www.flowparagliders.com.au/yoti-3-light', 721),
  ('Flow', 'Yoti 3 Light', '17', 'EN 926-1', 'Light miniwing', 'Current', 'https://www.flowparagliders.com.au/yoti-3-light', 722),
  ('Flow', 'Yoti 3 Light', '19', 'EN 926-1', 'Light miniwing', 'Current', 'https://www.flowparagliders.com.au/yoti-3-light', 723),
  ('Flow', 'Yoti 3 Light', '21', 'EN 926-1', 'Light miniwing', 'Current', 'https://www.flowparagliders.com.au/yoti-3-light', 724),
  ('Davinci', 'Duet Pro', '40', 'B', 'Tandem', 'Current', 'https://flydavinci.com/duet-pro', 725),
  ('Davinci', 'Duet Pro', '42', 'B', 'Tandem', 'Current', 'https://flydavinci.com/duet-pro', 726),
  ('Davinci', 'Popera', 'XS', 'D', 'Paraglider', 'Current', 'https://flydavinci.com/popera', 727),
  ('Davinci', 'Popera', 'S', 'D', 'Paraglider', 'Current', 'https://flydavinci.com/popera', 728),
  ('Davinci', 'Popera', 'M', 'D', 'Paraglider', 'Current', 'https://flydavinci.com/popera', 729),
  ('Davinci', 'Popera', 'L', 'D', 'Paraglider', 'Current', 'https://flydavinci.com/popera', 730),
  ('Davinci', 'Mambo', 'XS', 'C', 'Paraglider', 'Current', 'https://flydavinci.com/mambo', 731),
  ('Davinci', 'Mambo', 'S', 'C', 'Paraglider', 'Current', 'https://flydavinci.com/mambo', 732),
  ('Davinci', 'Mambo', 'M', 'C', 'Paraglider', 'Current', 'https://flydavinci.com/mambo', 733),
  ('Davinci', 'Mambo', 'L', 'C', 'Paraglider', 'Current', 'https://flydavinci.com/mambo', 734),
  ('Davinci', 'Tango', 'XS', 'C', 'Paraglider', 'Current', 'https://flydavinci.com/tango', 735),
  ('Davinci', 'Tango', 'S', 'C', 'Paraglider', 'Current', 'https://flydavinci.com/tango', 736),
  ('Davinci', 'Tango', 'M', 'C', 'Paraglider', 'Current', 'https://flydavinci.com/tango', 737),
  ('Davinci', 'Tango', 'L', 'C', 'Paraglider', 'Current', 'https://flydavinci.com/tango', 738),
  ('Davinci', 'Funky 2', 'XS', 'B', 'Paraglider', 'Current', 'https://flydavinci.com/funky-2', 739),
  ('Davinci', 'Funky 2', 'S', 'B', 'Paraglider', 'Current', 'https://flydavinci.com/funky-2', 740),
  ('Davinci', 'Funky 2', 'M', 'B', 'Paraglider', 'Current', 'https://flydavinci.com/funky-2', 741),
  ('Davinci', 'Funky 2', 'L', 'B', 'Paraglider', 'Current', 'https://flydavinci.com/funky-2', 742),
  ('Davinci', 'Classic 2', 'XS', 'A', 'Paraglider', 'Current', 'https://flydavinci.com/classic-2', 743),
  ('Davinci', 'Classic 2', 'S', 'A', 'Paraglider', 'Current', 'https://flydavinci.com/classic-2', 744),
  ('Davinci', 'Classic 2', 'M', 'A', 'Paraglider', 'Current', 'https://flydavinci.com/classic-2', 745),
  ('Davinci', 'Classic 2', 'L', 'A', 'Paraglider', 'Current', 'https://flydavinci.com/classic-2', 746),
  ('Davinci', 'Hula', '19', 'A', 'Hike and fly', 'Current', 'https://flydavinci.com/hula', 747),
  ('Davinci', 'Hula', '21', 'A', 'Hike and fly', 'Current', 'https://flydavinci.com/hula', 748),
  ('Davinci', 'Hula', '23', 'A', 'Hike and fly', 'Current', 'https://flydavinci.com/hula', 749),
  ('Davinci', 'Hula', '25', 'A', 'Hike and fly', 'Current', 'https://flydavinci.com/hula', 750),
  ('Davinci', 'Hula', '27', 'A', 'Hike and fly', 'Current', 'https://flydavinci.com/hula', 751),
  ('Davinci', 'Hula', '29', 'A', 'Hike and fly', 'Current', 'https://flydavinci.com/hula', 752),
  ('Davinci', 'Rhythm 2', 'XXS', 'A', 'Paraglider', 'Current', 'https://flydavinci.com/rhythm-2', 753),
  ('Davinci', 'Rhythm 2', 'XS', 'A', 'Paraglider', 'Current', 'https://flydavinci.com/rhythm-2', 754),
  ('Davinci', 'Rhythm 2', 'S', 'A', 'Paraglider', 'Current', 'https://flydavinci.com/rhythm-2', 755),
  ('Davinci', 'Rhythm 2', 'M', 'A', 'Paraglider', 'Current', 'https://flydavinci.com/rhythm-2', 756),
  ('Davinci', 'Rhythm 2', 'L', 'A', 'Paraglider', 'Current', 'https://flydavinci.com/rhythm-2', 757),
  ('Davinci', 'Point 2', 'XXS', 'A', 'Paraglider', 'Current', 'https://flydavinci.com/point-2', 758),
  ('Davinci', 'Point 2', 'XS', 'A', 'Paraglider', 'Current', 'https://flydavinci.com/point-2', 759),
  ('Davinci', 'Point 2', 'S', 'A', 'Paraglider', 'Current', 'https://flydavinci.com/point-2', 760),
  ('Davinci', 'Point 2', 'M', 'A', 'Paraglider', 'Current', 'https://flydavinci.com/point-2', 761),
  ('Davinci', 'Point 2', 'L', 'A', 'Paraglider', 'Current', 'https://flydavinci.com/point-2', 762),
  ('Davinci', 'Point 2', 'XL', 'A', 'Paraglider', 'Current', 'https://flydavinci.com/point-2', 763),
  ('Davinci', 'DOREMI', '16', 'EN 926-1', 'Miniwing', 'Current', 'https://flydavinci.com/doremi', 764),
  ('Davinci', 'DOREMI', '18', 'EN 926-1', 'Miniwing', 'Current', 'https://flydavinci.com/doremi', 765),
  ('Davinci', 'DOREMI', '20', 'EN 926-1', 'Miniwing', 'Current', 'https://flydavinci.com/doremi', 766),
  ('Davinci', 'Tune', '20', 'EN 926-1', 'Miniwing', 'Current', 'https://flydavinci.com/tune', 767),
  ('Davinci', 'Tune', '22', 'EN 926-1', 'Miniwing', 'Current', 'https://flydavinci.com/tune', 768),
  ('Davinci', 'Tune', '24', 'EN 926-1', 'Miniwing', 'Current', 'https://flydavinci.com/tune', 769),
  ('Davinci', 'Tune', '26', 'EN 926-1', 'Miniwing', 'Current', 'https://flydavinci.com/tune', 770),
  ('Davinci', 'Tune', '28', 'EN 926-1', 'Miniwing', 'Current', 'https://flydavinci.com/tune', 771);
--> statement-breakpoint
ALTER TABLE "flights" DROP CONSTRAINT "flights_glider_hours_credited_seconds_nonnegative";--> statement-breakpoint
ALTER TABLE "flights" DROP CONSTRAINT "flights_glider_hours_generation_nonnegative";--> statement-breakpoint
ALTER TABLE "flights" DROP CONSTRAINT "flights_glider_hours_credit_complete";--> statement-breakpoint
ALTER TABLE "profiles" DROP CONSTRAINT "profiles_glider_hours_generation_nonnegative";--> statement-breakpoint
ALTER TABLE "profiles" ADD COLUMN "glider_model_id" uuid;--> statement-breakpoint
ALTER TABLE "profiles" DROP CONSTRAINT IF EXISTS "profiles_glider_identity_complete";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN "glider_manufacturer";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN "glider_model";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN "glider_size";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN "glider_en_rating";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN "glider_hours_generation";--> statement-breakpoint
ALTER TABLE "flights" DROP COLUMN "glider_hours_credited_seconds";--> statement-breakpoint
ALTER TABLE "flights" DROP COLUMN "glider_hours_generation";--> statement-breakpoint
UPDATE "profiles"
SET "glider_year" = NULL,
	"glider_competition_id" = NULL;--> statement-breakpoint
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_glider_model_id_glider_models_id_fkey" FOREIGN KEY ("glider_model_id") REFERENCES "glider_models"("id");--> statement-breakpoint
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_glider_identity_complete" CHECK (("glider_model_id" IS NULL AND "glider_year" IS NULL)
        OR ("glider_model_id" IS NOT NULL AND "glider_year" IS NOT NULL));
