import { describe, expect, it, vi } from 'vitest';
// @ts-expect-error Browser asset is JavaScript.
import { initializeMapReplayController } from '../../public/scripts/mapReplayController.js';

function element() {
  const listeners: Record<string, Set<Function>> = {};
  return {
    hidden: false, disabled: false, textContent: '', value: '1', max: '', dataset: {},
    addEventListener(type: string, cb: Function) { (listeners[type] ??= new Set()).add(cb); },
    removeEventListener(type: string, cb: Function) { listeners[type]?.delete(cb); },
    click() { listeners.click?.forEach((cb) => cb({})); },
    input() { listeners.input?.forEach((cb) => cb({})); },
    change() { listeners.change?.forEach((cb) => cb({})); },
    listenerCount(type: string) { return listeners[type]?.size ?? 0; },
    setAttribute() {},
  };
}
function setup(month?: string) {
  const root: any = element();
  const nodes: any = Object.fromEntries(['[data-map-replay-open]', '[data-map-replay-panel]', '[data-map-replay-status]', '[data-map-replay-play]', '[data-map-replay-close]', '[data-map-replay-slider]', '[data-map-replay-elapsed]', '[data-map-replay-speed]'].map((key) => [key, element()]));
  root.querySelector = (s: string) => nodes[s];
  return { documentRef: { querySelector: () => root } as any, nodes, month };
}
const map = { getBounds: () => ({ getWest: () => -1, getSouth: () => 2, getEast: () => 3, getNorth: () => 4 }) } as any;
const flights = [{ flightId: 'f1', pilotUserId: 'p1', durationMs: 1000, points: [[0, 0, 0], [1, 1, 1000]] }];

describe('map replay controller', () => {
  it('hides entry without month and shows it after setMonth', () => { const s = setup(); const c: any = initializeMapReplayController({ ...s, map, fetchImpl: vi.fn() }); expect(s.nodes['[data-map-replay-open]'].hidden).toBe(true); c.setMonth('2026-02'); expect(s.nodes['[data-map-replay-open]'].hidden).toBe(false); });
  it('fetches captured bounds, mode and month once per open', async () => { const s = setup('2026-01'); const fetch = vi.fn((..._args: [string]) => Promise.resolve({ ok: true, json: async () => ({ flights: [] }) })); const c: any = initializeMapReplayController({ ...s, map, mode: 'personal', fetchImpl: fetch }); s.nodes['[data-map-replay-open]'].click(); await vi.waitFor(() => expect(fetch).toHaveBeenCalledTimes(1)); s.nodes['[data-map-replay-open]'].click(); expect(fetch).toHaveBeenCalledTimes(1); const url = fetch.mock.calls[0]![0]; expect(url).toContain('month=2026-01'); expect(url).toContain('mode=personal'); expect(url).toContain('west=-1'); expect(url).toContain('south=2'); expect(url).toContain('east=3'); expect(url).toContain('north=4'); c.close(); });
  it('normalizes wrapped world bounds before requesting replay data', async () => { const s = setup('2026-01'); const wrappedMap = { getBounds: () => ({ getWest: () => 181, getSouth: () => 2, getEast: () => 543, getNorth: () => 4 }) } as any; const fetch = vi.fn(async (..._args: [string]) => ({ ok: true, json: async () => ({ flights: [] }) })); initializeMapReplayController({ ...s, map: wrappedMap, fetchImpl: fetch }); s.nodes['[data-map-replay-open]'].click(); await vi.waitFor(() => expect(fetch).toHaveBeenCalledTimes(1)); const url = new URL(String(fetch.mock.calls[0]?.[0]), 'https://example.test'); expect(url.searchParams.get('west')).toBe('-180'); expect(url.searchParams.get('east')).toBe('180'); });
  it('supports competitive mode and forwards the pilot color callback', async () => { const s = setup('2026-01'); const fetch = vi.fn((..._args: [string]) => Promise.resolve({ ok: true, json: async () => ({ flights }) })); const colorForPilot = vi.fn(() => '#abc'); const installLayer = vi.fn(() => ({ update() {}, close() {} })); initializeMapReplayController({ ...s, map, mode: 'competitive', fetchImpl: fetch, colorForPilot, installLayer }); s.nodes['[data-map-replay-open]'].click(); await vi.waitFor(() => expect(installLayer).toHaveBeenCalled()); expect(fetch.mock.calls[0]![0]).toContain('mode=competitive'); expect(installLayer).toHaveBeenCalledWith(map, { colorForPilot }); });
  it('loads paused timeline, forwards controls, and closes both resources', async () => { const s = setup('2026-01'); const timeline: any = { subscribe: (cb: any) => { timeline.cb = cb; cb({ elapsedMs: 0, duration: 1000, playing: false }); }, snapshot: () => ({ playing: false }), play: vi.fn(), pause: vi.fn(), setRate: vi.fn(), seek: vi.fn(), destroy: vi.fn() }; const layer: any = { update: vi.fn(), close: vi.fn() }; const c: any = initializeMapReplayController({ ...s, map, fetchImpl: vi.fn(async () => ({ ok: true, json: async () => ({ flights }) })), createTimeline: vi.fn(() => timeline), installLayer: vi.fn(() => layer) }); s.nodes['[data-map-replay-open]'].click(); await vi.waitFor(() => expect(s.nodes['[data-map-replay-play]'].disabled).toBe(false)); expect(timeline.play).not.toHaveBeenCalled(); s.nodes['[data-map-replay-play]'].click(); expect(timeline.play).toHaveBeenCalled(); timeline.snapshot = () => ({ playing: true }); s.nodes['[data-map-replay-play]'].click(); expect(timeline.pause).toHaveBeenCalled(); for (const rate of ['1', '2', '5', '20', '60']) { s.nodes['[data-map-replay-speed]'].value = rate; s.nodes['[data-map-replay-speed]'].change(); } expect(timeline.setRate).toHaveBeenCalledWith(60); s.nodes['[data-map-replay-slider]'].value = '400'; s.nodes['[data-map-replay-slider]'].input(); expect(timeline.seek).toHaveBeenCalledWith(400); s.nodes['[data-map-replay-close]'].click(); expect(timeline.destroy).toHaveBeenCalled(); expect(layer.close).toHaveBeenCalled(); });
  it('disables play while loading and permits retry after empty or error responses', async () => { const s = setup('2026-01'); let attempt = 0; const fetch = vi.fn(async () => { attempt += 1; if (attempt === 1) return { ok: true, json: async () => ({ flights: [] }) }; return { ok: false, json: async () => ({}) }; }); const c: any = initializeMapReplayController({ ...s, map, fetchImpl: fetch }); const opening = s.nodes['[data-map-replay-open]']; opening.click(); expect(s.nodes['[data-map-replay-play]'].disabled).toBe(true); await vi.waitFor(() => expect(s.nodes['[data-map-replay-status]'].textContent).toContain('No flights')); expect(opening.hidden).toBe(false); opening.click(); await vi.waitFor(() => expect(s.nodes['[data-map-replay-status]'].textContent).toContain('unavailable')); expect(fetch).toHaveBeenCalledTimes(2); });
  it('supports empty/error retry and invalidates stale pending requests', async () => { const s = setup('2026-01'); let resolve!: Function; const fetch = vi.fn(() => new Promise((r) => { resolve = r; })); const c: any = initializeMapReplayController({ ...s, map, fetchImpl: fetch }); s.nodes['[data-map-replay-open]'].click(); c.setMonth('2026-02'); resolve({ ok: true, json: async () => ({ flights }) }); await Promise.resolve(); s.nodes['[data-map-replay-open]'].click(); expect(fetch).toHaveBeenCalledTimes(2); });
  it('does not let a stale failed request tear down a newer replay', async () => { const s = setup('2026-01'); let rejectA!: (error: Error) => void; let resolveB!: (value: any) => void; const fetch = vi.fn((..._args: [string]) => fetch.mock.calls.length === 1 ? new Promise((_resolve, reject) => { rejectA = reject; }) : new Promise((resolve) => { resolveB = resolve; })); const layer: any = { update: vi.fn(), close: vi.fn() }; const timeline: any = { subscribe: vi.fn(), destroy: vi.fn(), snapshot: () => ({ playing: false }) }; const c: any = initializeMapReplayController({ ...s, map, fetchImpl: fetch, installLayer: vi.fn(() => layer), createTimeline: vi.fn(() => timeline) }); s.nodes['[data-map-replay-open]'].click(); c.setMonth('2026-02'); s.nodes['[data-map-replay-open]'].click(); resolveB({ ok: true, json: async () => ({ flights }) }); await vi.waitFor(() => expect(s.nodes['[data-map-replay-play]'].disabled).toBe(false)); rejectA(new Error('stale')); await Promise.resolve(); expect(layer.close).not.toHaveBeenCalled(); expect(timeline.destroy).not.toHaveBeenCalled(); });
  it('removes listeners on destroy', () => { const s = setup('2026-01'); const c: any = initializeMapReplayController({ ...s, map, fetchImpl: vi.fn() }); c.destroy(); expect(s.nodes['[data-map-replay-open]'].listenerCount('click')).toBe(0); expect(s.nodes['[data-map-replay-play]'].listenerCount('click')).toBe(0); });
});
